// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package common // import "github.com/brocaar/loraserver/api/common"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Modulation int32

const (
	// LoRa
	Modulation_LORA Modulation = 0
	// FSK
	Modulation_FSK Modulation = 1
)

var Modulation_name = map[int32]string{
	0: "LORA",
	1: "FSK",
}
var Modulation_value = map[string]int32{
	"LORA": 0,
	"FSK":  1,
}

func (x Modulation) String() string {
	return proto.EnumName(Modulation_name, int32(x))
}
func (Modulation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_97d158ed01478cb1, []int{0}
}

type Region int32

const (
	// EU868
	Region_EU868 Region = 0
	// US915
	Region_US915 Region = 2
	// CN779
	Region_CN779 Region = 3
	// EU433
	Region_EU433 Region = 4
	// AU915
	Region_AU915 Region = 5
	// CN470
	Region_CN470 Region = 6
	// AS923
	Region_AS923 Region = 7
	// KR920
	Region_KR920 Region = 8
	// IN865
	Region_IN865 Region = 9
	// RU864
	Region_RU864 Region = 10
)

var Region_name = map[int32]string{
	0:  "EU868",
	2:  "US915",
	3:  "CN779",
	4:  "EU433",
	5:  "AU915",
	6:  "CN470",
	7:  "AS923",
	8:  "KR920",
	9:  "IN865",
	10: "RU864",
}
var Region_value = map[string]int32{
	"EU868": 0,
	"US915": 2,
	"CN779": 3,
	"EU433": 4,
	"AU915": 5,
	"CN470": 6,
	"AS923": 7,
	"KR920": 8,
	"IN865": 9,
	"RU864": 10,
}

func (x Region) String() string {
	return proto.EnumName(Region_name, int32(x))
}
func (Region) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_97d158ed01478cb1, []int{1}
}

type KeyEnvelope struct {
	// KEK label.
	KekLabel string `protobuf:"bytes,1,opt,name=kek_label,json=kekLabel,proto3" json:"kek_label,omitempty"`
	// AES key (when the kek_label is set, this key is encrypted using a key
	// known to the join-server and application-server.
	// For more information please refer to the LoRaWAN Backend Interface
	// 'Key Transport Security' section.
	AesKey               []byte   `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyEnvelope) Reset()         { *m = KeyEnvelope{} }
func (m *KeyEnvelope) String() string { return proto.CompactTextString(m) }
func (*KeyEnvelope) ProtoMessage()    {}
func (*KeyEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_97d158ed01478cb1, []int{0}
}
func (m *KeyEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyEnvelope.Unmarshal(m, b)
}
func (m *KeyEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyEnvelope.Marshal(b, m, deterministic)
}
func (dst *KeyEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyEnvelope.Merge(dst, src)
}
func (m *KeyEnvelope) XXX_Size() int {
	return xxx_messageInfo_KeyEnvelope.Size(m)
}
func (m *KeyEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_KeyEnvelope proto.InternalMessageInfo

func (m *KeyEnvelope) GetKekLabel() string {
	if m != nil {
		return m.KekLabel
	}
	return ""
}

func (m *KeyEnvelope) GetAesKey() []byte {
	if m != nil {
		return m.AesKey
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyEnvelope)(nil), "common.KeyEnvelope")
	proto.RegisterEnum("common.Modulation", Modulation_name, Modulation_value)
	proto.RegisterEnum("common.Region", Region_name, Region_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_97d158ed01478cb1) }

var fileDescriptor_common_97d158ed01478cb1 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0xd0, 0xcb, 0x6f, 0xb2, 0x40,
	0x14, 0x05, 0x70, 0xf1, 0x81, 0x32, 0x9f, 0x8b, 0x1b, 0x36, 0x9f, 0x49, 0x17, 0x35, 0x5d, 0x11,
	0x16, 0x62, 0x05, 0x79, 0x2c, 0xad, 0xb1, 0x49, 0x83, 0xb5, 0xc9, 0x10, 0x36, 0xdd, 0x98, 0x81,
	0xde, 0x58, 0xc2, 0x63, 0xc8, 0x80, 0x24, 0xfc, 0xf7, 0xcd, 0xc8, 0xee, 0x77, 0xee, 0x3d, 0xab,
	0x43, 0x96, 0x29, 0x2f, 0x4b, 0x5e, 0x6d, 0x6a, 0xc1, 0x5b, 0xae, 0xab, 0x43, 0x7a, 0x39, 0x92,
	0x7f, 0x21, 0xf6, 0xa7, 0xaa, 0xc3, 0x82, 0xd7, 0xa8, 0x3f, 0x11, 0x2d, 0xc7, 0xfc, 0x5a, 0xb0,
	0x04, 0x8b, 0x95, 0xb2, 0x56, 0x0c, 0x8d, 0x2e, 0x72, 0xcc, 0xcf, 0x32, 0xeb, 0xff, 0xc9, 0x9c,
	0x61, 0x73, 0xcd, 0xb1, 0x5f, 0x8d, 0xd7, 0x8a, 0xb1, 0xa4, 0x2a, 0xc3, 0x26, 0xc4, 0xde, 0x7c,
	0x26, 0xe4, 0x93, 0xff, 0xdc, 0x0b, 0xd6, 0x66, 0xbc, 0xd2, 0x17, 0x64, 0x7a, 0xfe, 0xa2, 0x07,
	0x18, 0xe9, 0x73, 0x32, 0x79, 0x8f, 0x42, 0x50, 0xcc, 0x8e, 0xa8, 0x14, 0x6f, 0xf2, 0xa9, 0x91,
	0xd9, 0x29, 0xf6, 0x5d, 0x1f, 0x46, 0x92, 0x71, 0x14, 0xbc, 0xee, 0x61, 0x2c, 0x79, 0xbc, 0x78,
	0x5e, 0x00, 0x93, 0xa1, 0xe0, 0xd8, 0x36, 0x4c, 0x25, 0x0f, 0xb1, 0x2c, 0xcc, 0x86, 0x82, 0xe3,
	0x6d, 0x41, 0x7d, 0x5c, 0xa3, 0x60, 0x67, 0xc3, 0x5c, 0x32, 0xa4, 0xc1, 0x6e, 0x0b, 0x0b, 0xc9,
	0x8f, 0x8b, 0xef, 0xee, 0x41, 0x93, 0xa4, 0xb1, 0xef, 0x3a, 0x40, 0xde, 0xcc, 0x6f, 0xe3, 0x96,
	0xb5, 0xbf, 0xf7, 0x64, 0x93, 0xf2, 0xd2, 0x4a, 0x04, 0x4f, 0x19, 0x13, 0x56, 0xc1, 0x05, 0x6b,
	0x50, 0x74, 0x28, 0x2c, 0x56, 0x67, 0xd6, 0xb0, 0x44, 0xa2, 0x3e, 0x86, 0xb1, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xe5, 0xc9, 0x90, 0xcd, 0x28, 0x01, 0x00, 0x00,
}
