project_name: loraserver

builds:
  - main: cmd/loraserver/main.go
    binary: loraserver
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

release:
  disable: true

nfpm:
  vendor: LoRa Server project
  homepage: https://www.loraserver.io/
  maintainer: Orne Brocaar <info@brocaar.com>
  description: LoRa Server
  license: MIT
  formats:
    - deb
  bindir: /usr/bin
  files:
    "packaging/files/loraserver.rotate": "/etc/logrotate.d/loraserver"
    "packaging/files/loraserver.init": "/usr/lib/loraserver/scripts/loraserver.init"
    "packaging/files/loraserver.service": "/usr/lib/loraserver/scripts/loraserver.service"
  scripts:
    postinstall: "packaging/scripts/post-install.sh"
    postremove: "packaging/scripts/post-remove.sh"
