// Code generated by protoc-gen-go. DO NOT EDIT.
// source: downlink_frames.proto

package storage

import (
	fmt "fmt"
	gw "github.com/brocaar/chirpstack-api/go/gw"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownlinkFrames struct {
	// Token.
	Token uint32 `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
	// DevEUI.
	DevEui []byte `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Multicast Group ID.
	MulticastGroupId []byte `protobuf:"bytes,3,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// Downlink frames.
	DownlinkFrames       []*gw.DownlinkFrame `protobuf:"bytes,4,rep,name=downlink_frames,json=downlinkFrames,proto3" json:"downlink_frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DownlinkFrames) Reset()         { *m = DownlinkFrames{} }
func (m *DownlinkFrames) String() string { return proto.CompactTextString(m) }
func (*DownlinkFrames) ProtoMessage()    {}
func (*DownlinkFrames) Descriptor() ([]byte, []int) {
	return fileDescriptor_a06c04f39a283b6b, []int{0}
}

func (m *DownlinkFrames) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownlinkFrames.Unmarshal(m, b)
}
func (m *DownlinkFrames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownlinkFrames.Marshal(b, m, deterministic)
}
func (m *DownlinkFrames) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownlinkFrames.Merge(m, src)
}
func (m *DownlinkFrames) XXX_Size() int {
	return xxx_messageInfo_DownlinkFrames.Size(m)
}
func (m *DownlinkFrames) XXX_DiscardUnknown() {
	xxx_messageInfo_DownlinkFrames.DiscardUnknown(m)
}

var xxx_messageInfo_DownlinkFrames proto.InternalMessageInfo

func (m *DownlinkFrames) GetToken() uint32 {
	if m != nil {
		return m.Token
	}
	return 0
}

func (m *DownlinkFrames) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *DownlinkFrames) GetMulticastGroupId() []byte {
	if m != nil {
		return m.MulticastGroupId
	}
	return nil
}

func (m *DownlinkFrames) GetDownlinkFrames() []*gw.DownlinkFrame {
	if m != nil {
		return m.DownlinkFrames
	}
	return nil
}

func init() {
	proto.RegisterType((*DownlinkFrames)(nil), "storage.DownlinkFrames")
}

func init() { proto.RegisterFile("downlink_frames.proto", fileDescriptor_a06c04f39a283b6b) }

var fileDescriptor_a06c04f39a283b6b = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xc9, 0x2f, 0xcf,
	0xcb, 0xc9, 0xcc, 0xcb, 0x8e, 0x4f, 0x2b, 0x4a, 0xcc, 0x4d, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f, 0x95, 0xe2, 0x4f, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2f, 0xd7, 0x4f, 0x2f, 0x87, 0xc8, 0x28, 0xad, 0x64, 0xe4, 0xe2, 0x73, 0x81, 0xea, 0x71,
	0x03, 0x6b, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd, 0x93, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0d, 0x82, 0x70, 0x84, 0xc4, 0xb9, 0xd8, 0x53, 0x52, 0xcb, 0xe2, 0x53, 0x4b, 0x33, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xd8, 0x52, 0x52, 0xcb, 0x5c, 0x4b, 0x33, 0x85, 0x74, 0xb8,
	0x84, 0x72, 0x4b, 0x73, 0x4a, 0x32, 0x93, 0x13, 0x8b, 0x4b, 0xe2, 0xd3, 0x8b, 0xf2, 0x4b, 0x0b,
	0xe2, 0x33, 0x53, 0x24, 0x98, 0xc1, 0x6a, 0x04, 0xe0, 0x32, 0xee, 0x20, 0x09, 0xcf, 0x14, 0x21,
	0x2b, 0x2e, 0x7e, 0x34, 0x27, 0x4a, 0xb0, 0x28, 0x30, 0x6b, 0x70, 0x1b, 0x09, 0xea, 0xa5, 0x97,
	0xeb, 0xa1, 0xb8, 0x24, 0x88, 0x2f, 0x05, 0xc5, 0x61, 0x49, 0x6c, 0x60, 0x27, 0x1b, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0x9d, 0x53, 0xe6, 0xe5, 0x00, 0x00, 0x00,
}
