// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway_state.proto

package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GatewayState struct {
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// Last seen at timestamp.
	LastSeenAt           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GatewayState) Reset()         { *m = GatewayState{} }
func (m *GatewayState) String() string { return proto.CompactTextString(m) }
func (*GatewayState) ProtoMessage()    {}
func (*GatewayState) Descriptor() ([]byte, []int) {
	return fileDescriptor_db904b35cf8838c3, []int{0}
}
func (m *GatewayState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayState.Unmarshal(m, b)
}
func (m *GatewayState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayState.Marshal(b, m, deterministic)
}
func (dst *GatewayState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayState.Merge(dst, src)
}
func (m *GatewayState) XXX_Size() int {
	return xxx_messageInfo_GatewayState.Size(m)
}
func (m *GatewayState) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayState.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayState proto.InternalMessageInfo

func (m *GatewayState) GetGatewayId() []byte {
	if m != nil {
		return m.GatewayId
	}
	return nil
}

func (m *GatewayState) GetLastSeenAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeenAt
	}
	return nil
}

func init() {
	proto.RegisterType((*GatewayState)(nil), "storage.GatewayState")
}

func init() { proto.RegisterFile("gateway_state.proto", fileDescriptor_db904b35cf8838c3) }

var fileDescriptor_db904b35cf8838c3 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0x8c, 0x2f, 0x2e, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f, 0x95, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49,
	0xd5, 0x07, 0x0b, 0x27, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16,
	0x40, 0x54, 0x2a, 0x65, 0x73, 0xf1, 0xb8, 0x43, 0x0c, 0x08, 0x06, 0xe9, 0x17, 0x92, 0xe5, 0xe2,
	0x82, 0x19, 0x98, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0xc4, 0x09, 0x15, 0xf1, 0x4c,
	0x11, 0xb2, 0xe1, 0xe2, 0xc9, 0x49, 0x2c, 0x2e, 0x89, 0x2f, 0x4e, 0x4d, 0xcd, 0x8b, 0x4f, 0x2c,
	0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0x58, 0xa3, 0x07, 0xb3, 0x46, 0x2f,
	0x04, 0x66, 0x4d, 0x10, 0x17, 0x48, 0x7d, 0x70, 0x6a, 0x6a, 0x9e, 0x63, 0x49, 0x12, 0x1b, 0x58,
	0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xef, 0x75, 0x30, 0x38, 0xb4, 0x00, 0x00, 0x00,
}
