// Code generated by protoc-gen-go.
// source: as.proto
// DO NOT EDIT!

/*
Package as is a generated protocol buffer package.

It is generated from these files:
	as.proto

It has these top-level messages:
	DataRate
	RXInfo
	TXInfo
	JoinRequestRequest
	JoinRequestResponse
	HandleDataUpRequest
	GetDataDownRequest
	GetDataDownResponse
	HandleDataUpResponse
	HandleDataDownACKRequest
	HandleDataDownACKResponse
	HandleErrorRequest
	HandleErrorResponse
*/
package as

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RXWindow int32

const (
	RXWindow_RX1 RXWindow = 0
	RXWindow_RX2 RXWindow = 1
)

var RXWindow_name = map[int32]string{
	0: "RX1",
	1: "RX2",
}
var RXWindow_value = map[string]int32{
	"RX1": 0,
	"RX2": 1,
}

func (x RXWindow) String() string {
	return proto.EnumName(RXWindow_name, int32(x))
}
func (RXWindow) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorType int32

const (
	ErrorType_Generic      ErrorType = 0
	ErrorType_OTAA         ErrorType = 1
	ErrorType_DATA_UP_FCNT ErrorType = 2
	ErrorType_DATA_UP_MIC  ErrorType = 3
)

var ErrorType_name = map[int32]string{
	0: "Generic",
	1: "OTAA",
	2: "DATA_UP_FCNT",
	3: "DATA_UP_MIC",
}
var ErrorType_value = map[string]int32{
	"Generic":      0,
	"OTAA":         1,
	"DATA_UP_FCNT": 2,
	"DATA_UP_MIC":  3,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DataRate struct {
	Modulation   string `protobuf:"bytes,1,opt,name=modulation" json:"modulation,omitempty"`
	BandWidth    uint32 `protobuf:"varint,2,opt,name=bandWidth" json:"bandWidth,omitempty"`
	SpreadFactor uint32 `protobuf:"varint,3,opt,name=spreadFactor" json:"spreadFactor,omitempty"`
	Bitrate      uint32 `protobuf:"varint,4,opt,name=bitrate" json:"bitrate,omitempty"`
}

func (m *DataRate) Reset()                    { *m = DataRate{} }
func (m *DataRate) String() string            { return proto.CompactTextString(m) }
func (*DataRate) ProtoMessage()               {}
func (*DataRate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DataRate) GetModulation() string {
	if m != nil {
		return m.Modulation
	}
	return ""
}

func (m *DataRate) GetBandWidth() uint32 {
	if m != nil {
		return m.BandWidth
	}
	return 0
}

func (m *DataRate) GetSpreadFactor() uint32 {
	if m != nil {
		return m.SpreadFactor
	}
	return 0
}

func (m *DataRate) GetBitrate() uint32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

type RXInfo struct {
	Mac       []byte  `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Time      string  `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Rssi      int32   `protobuf:"varint,3,opt,name=rssi" json:"rssi,omitempty"`
	LoRaSNR   float64 `protobuf:"fixed64,4,opt,name=loRaSNR" json:"loRaSNR,omitempty"`
	Name      string  `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Latitude  float64 `protobuf:"fixed64,6,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,7,opt,name=longitude" json:"longitude,omitempty"`
	Altitude  float64 `protobuf:"fixed64,8,opt,name=altitude" json:"altitude,omitempty"`
}

func (m *RXInfo) Reset()                    { *m = RXInfo{} }
func (m *RXInfo) String() string            { return proto.CompactTextString(m) }
func (*RXInfo) ProtoMessage()               {}
func (*RXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RXInfo) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

func (m *RXInfo) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *RXInfo) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *RXInfo) GetLoRaSNR() float64 {
	if m != nil {
		return m.LoRaSNR
	}
	return 0
}

func (m *RXInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RXInfo) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *RXInfo) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *RXInfo) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type TXInfo struct {
	Frequency int64     `protobuf:"varint,1,opt,name=frequency" json:"frequency,omitempty"`
	DataRate  *DataRate `protobuf:"bytes,2,opt,name=dataRate" json:"dataRate,omitempty"`
	Adr       bool      `protobuf:"varint,3,opt,name=adr" json:"adr,omitempty"`
	CodeRate  string    `protobuf:"bytes,4,opt,name=codeRate" json:"codeRate,omitempty"`
}

func (m *TXInfo) Reset()                    { *m = TXInfo{} }
func (m *TXInfo) String() string            { return proto.CompactTextString(m) }
func (*TXInfo) ProtoMessage()               {}
func (*TXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TXInfo) GetFrequency() int64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *TXInfo) GetDataRate() *DataRate {
	if m != nil {
		return m.DataRate
	}
	return nil
}

func (m *TXInfo) GetAdr() bool {
	if m != nil {
		return m.Adr
	}
	return false
}

func (m *TXInfo) GetCodeRate() string {
	if m != nil {
		return m.CodeRate
	}
	return ""
}

type JoinRequestRequest struct {
	// PHYPayload of the join-request.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phyPayload,proto3" json:"phyPayload,omitempty"`
	// DevAddr assigned by the network-server.
	DevAddr []byte `protobuf:"bytes,2,opt,name=devAddr,proto3" json:"devAddr,omitempty"`
	// NetID assigned by the network-server.
	NetID []byte `protobuf:"bytes,3,opt,name=netID,proto3" json:"netID,omitempty"`
	// Custom channels to add to the join-accept response.
	CFList []uint32 `protobuf:"varint,4,rep,packed,name=cFList" json:"cFList,omitempty"`
}

func (m *JoinRequestRequest) Reset()                    { *m = JoinRequestRequest{} }
func (m *JoinRequestRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequestRequest) ProtoMessage()               {}
func (*JoinRequestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JoinRequestRequest) GetPhyPayload() []byte {
	if m != nil {
		return m.PhyPayload
	}
	return nil
}

func (m *JoinRequestRequest) GetDevAddr() []byte {
	if m != nil {
		return m.DevAddr
	}
	return nil
}

func (m *JoinRequestRequest) GetNetID() []byte {
	if m != nil {
		return m.NetID
	}
	return nil
}

func (m *JoinRequestRequest) GetCFList() []uint32 {
	if m != nil {
		return m.CFList
	}
	return nil
}

type JoinRequestResponse struct {
	// The encrypted PHYPayload containing the join-accept.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phyPayload,proto3" json:"phyPayload,omitempty"`
	// The network-session key (16 bytes).
	NwkSKey []byte `protobuf:"bytes,2,opt,name=nwkSKey,proto3" json:"nwkSKey,omitempty"`
	// the RX delay value (0 = 1 sec, 1 = 1 sec, 2 = 2 sec ...).
	RxDelay uint32 `protobuf:"varint,3,opt,name=rxDelay" json:"rxDelay,omitempty"`
	// The data-rate offset used for RX1 (see LoRaWAN specs for valid values).
	Rx1DROffset uint32 `protobuf:"varint,4,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	// The RX window to use for downlink transmissions.
	RxWindow RXWindow `protobuf:"varint,6,opt,name=rxWindow,enum=as.RXWindow" json:"rxWindow,omitempty"`
	// The data-rate to use for RX2 transmissions.
	Rx2DR uint32 `protobuf:"varint,7,opt,name=rx2DR" json:"rx2DR,omitempty"`
	// The data-rate to use for RX2 transmissions.
	RelaxFCnt bool `protobuf:"varint,8,opt,name=relaxFCnt" json:"relaxFCnt,omitempty"`
	// The interval (based on frame-counter) on which to calculate the ideal
	// data-rate and tx-power of the node and if needed, request an adaption.
	AdrInterval uint32 `protobuf:"varint,9,opt,name=adrInterval" json:"adrInterval,omitempty"`
	// The installation margin to take into account when calculating the ideal
	// data-rate and tx-power. The default recommended value is 5dB.
	InstallationMargin float64 `protobuf:"fixed64,10,opt,name=installationMargin" json:"installationMargin,omitempty"`
}

func (m *JoinRequestResponse) Reset()                    { *m = JoinRequestResponse{} }
func (m *JoinRequestResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinRequestResponse) ProtoMessage()               {}
func (*JoinRequestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *JoinRequestResponse) GetPhyPayload() []byte {
	if m != nil {
		return m.PhyPayload
	}
	return nil
}

func (m *JoinRequestResponse) GetNwkSKey() []byte {
	if m != nil {
		return m.NwkSKey
	}
	return nil
}

func (m *JoinRequestResponse) GetRxDelay() uint32 {
	if m != nil {
		return m.RxDelay
	}
	return 0
}

func (m *JoinRequestResponse) GetRx1DROffset() uint32 {
	if m != nil {
		return m.Rx1DROffset
	}
	return 0
}

func (m *JoinRequestResponse) GetRxWindow() RXWindow {
	if m != nil {
		return m.RxWindow
	}
	return RXWindow_RX1
}

func (m *JoinRequestResponse) GetRx2DR() uint32 {
	if m != nil {
		return m.Rx2DR
	}
	return 0
}

func (m *JoinRequestResponse) GetRelaxFCnt() bool {
	if m != nil {
		return m.RelaxFCnt
	}
	return false
}

func (m *JoinRequestResponse) GetAdrInterval() uint32 {
	if m != nil {
		return m.AdrInterval
	}
	return 0
}

func (m *JoinRequestResponse) GetInstallationMargin() float64 {
	if m != nil {
		return m.InstallationMargin
	}
	return 0
}

type HandleDataUpRequest struct {
	DevEUI []byte    `protobuf:"bytes,1,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	AppEUI []byte    `protobuf:"bytes,2,opt,name=appEUI,proto3" json:"appEUI,omitempty"`
	FCnt   uint32    `protobuf:"varint,3,opt,name=fCnt" json:"fCnt,omitempty"`
	FPort  uint32    `protobuf:"varint,4,opt,name=fPort" json:"fPort,omitempty"`
	Data   []byte    `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	TxInfo *TXInfo   `protobuf:"bytes,6,opt,name=txInfo" json:"txInfo,omitempty"`
	RxInfo []*RXInfo `protobuf:"bytes,7,rep,name=rxInfo" json:"rxInfo,omitempty"`
}

func (m *HandleDataUpRequest) Reset()                    { *m = HandleDataUpRequest{} }
func (m *HandleDataUpRequest) String() string            { return proto.CompactTextString(m) }
func (*HandleDataUpRequest) ProtoMessage()               {}
func (*HandleDataUpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HandleDataUpRequest) GetDevEUI() []byte {
	if m != nil {
		return m.DevEUI
	}
	return nil
}

func (m *HandleDataUpRequest) GetAppEUI() []byte {
	if m != nil {
		return m.AppEUI
	}
	return nil
}

func (m *HandleDataUpRequest) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *HandleDataUpRequest) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *HandleDataUpRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *HandleDataUpRequest) GetTxInfo() *TXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *HandleDataUpRequest) GetRxInfo() []*RXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

type GetDataDownRequest struct {
	DevEUI         []byte `protobuf:"bytes,1,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	AppEUI         []byte `protobuf:"bytes,2,opt,name=appEUI,proto3" json:"appEUI,omitempty"`
	MaxPayloadSize uint32 `protobuf:"varint,3,opt,name=maxPayloadSize" json:"maxPayloadSize,omitempty"`
	FCnt           uint32 `protobuf:"varint,4,opt,name=fCnt" json:"fCnt,omitempty"`
}

func (m *GetDataDownRequest) Reset()                    { *m = GetDataDownRequest{} }
func (m *GetDataDownRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDataDownRequest) ProtoMessage()               {}
func (*GetDataDownRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetDataDownRequest) GetDevEUI() []byte {
	if m != nil {
		return m.DevEUI
	}
	return nil
}

func (m *GetDataDownRequest) GetAppEUI() []byte {
	if m != nil {
		return m.AppEUI
	}
	return nil
}

func (m *GetDataDownRequest) GetMaxPayloadSize() uint32 {
	if m != nil {
		return m.MaxPayloadSize
	}
	return 0
}

func (m *GetDataDownRequest) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

type GetDataDownResponse struct {
	Data      []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Confirmed bool   `protobuf:"varint,2,opt,name=confirmed" json:"confirmed,omitempty"`
	FPort     uint32 `protobuf:"varint,3,opt,name=fPort" json:"fPort,omitempty"`
	MoreData  bool   `protobuf:"varint,4,opt,name=moreData" json:"moreData,omitempty"`
}

func (m *GetDataDownResponse) Reset()                    { *m = GetDataDownResponse{} }
func (m *GetDataDownResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDataDownResponse) ProtoMessage()               {}
func (*GetDataDownResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetDataDownResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetDataDownResponse) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *GetDataDownResponse) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *GetDataDownResponse) GetMoreData() bool {
	if m != nil {
		return m.MoreData
	}
	return false
}

type HandleDataUpResponse struct {
}

func (m *HandleDataUpResponse) Reset()                    { *m = HandleDataUpResponse{} }
func (m *HandleDataUpResponse) String() string            { return proto.CompactTextString(m) }
func (*HandleDataUpResponse) ProtoMessage()               {}
func (*HandleDataUpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type HandleDataDownACKRequest struct {
	DevEUI []byte `protobuf:"bytes,1,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	AppEUI []byte `protobuf:"bytes,2,opt,name=appEUI,proto3" json:"appEUI,omitempty"`
	FCnt   uint32 `protobuf:"varint,3,opt,name=fCnt" json:"fCnt,omitempty"`
}

func (m *HandleDataDownACKRequest) Reset()                    { *m = HandleDataDownACKRequest{} }
func (m *HandleDataDownACKRequest) String() string            { return proto.CompactTextString(m) }
func (*HandleDataDownACKRequest) ProtoMessage()               {}
func (*HandleDataDownACKRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *HandleDataDownACKRequest) GetDevEUI() []byte {
	if m != nil {
		return m.DevEUI
	}
	return nil
}

func (m *HandleDataDownACKRequest) GetAppEUI() []byte {
	if m != nil {
		return m.AppEUI
	}
	return nil
}

func (m *HandleDataDownACKRequest) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

type HandleDataDownACKResponse struct {
}

func (m *HandleDataDownACKResponse) Reset()                    { *m = HandleDataDownACKResponse{} }
func (m *HandleDataDownACKResponse) String() string            { return proto.CompactTextString(m) }
func (*HandleDataDownACKResponse) ProtoMessage()               {}
func (*HandleDataDownACKResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type HandleErrorRequest struct {
	DevEUI []byte    `protobuf:"bytes,1,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	AppEUI []byte    `protobuf:"bytes,2,opt,name=appEUI,proto3" json:"appEUI,omitempty"`
	Type   ErrorType `protobuf:"varint,3,opt,name=type,enum=as.ErrorType" json:"type,omitempty"`
	Error  string    `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *HandleErrorRequest) Reset()                    { *m = HandleErrorRequest{} }
func (m *HandleErrorRequest) String() string            { return proto.CompactTextString(m) }
func (*HandleErrorRequest) ProtoMessage()               {}
func (*HandleErrorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *HandleErrorRequest) GetDevEUI() []byte {
	if m != nil {
		return m.DevEUI
	}
	return nil
}

func (m *HandleErrorRequest) GetAppEUI() []byte {
	if m != nil {
		return m.AppEUI
	}
	return nil
}

func (m *HandleErrorRequest) GetType() ErrorType {
	if m != nil {
		return m.Type
	}
	return ErrorType_Generic
}

func (m *HandleErrorRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type HandleErrorResponse struct {
}

func (m *HandleErrorResponse) Reset()                    { *m = HandleErrorResponse{} }
func (m *HandleErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*HandleErrorResponse) ProtoMessage()               {}
func (*HandleErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*DataRate)(nil), "as.DataRate")
	proto.RegisterType((*RXInfo)(nil), "as.RXInfo")
	proto.RegisterType((*TXInfo)(nil), "as.TXInfo")
	proto.RegisterType((*JoinRequestRequest)(nil), "as.JoinRequestRequest")
	proto.RegisterType((*JoinRequestResponse)(nil), "as.JoinRequestResponse")
	proto.RegisterType((*HandleDataUpRequest)(nil), "as.HandleDataUpRequest")
	proto.RegisterType((*GetDataDownRequest)(nil), "as.GetDataDownRequest")
	proto.RegisterType((*GetDataDownResponse)(nil), "as.GetDataDownResponse")
	proto.RegisterType((*HandleDataUpResponse)(nil), "as.HandleDataUpResponse")
	proto.RegisterType((*HandleDataDownACKRequest)(nil), "as.HandleDataDownACKRequest")
	proto.RegisterType((*HandleDataDownACKResponse)(nil), "as.HandleDataDownACKResponse")
	proto.RegisterType((*HandleErrorRequest)(nil), "as.HandleErrorRequest")
	proto.RegisterType((*HandleErrorResponse)(nil), "as.HandleErrorResponse")
	proto.RegisterEnum("as.RXWindow", RXWindow_name, RXWindow_value)
	proto.RegisterEnum("as.ErrorType", ErrorType_name, ErrorType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApplicationServer service

type ApplicationServerClient interface {
	// JoinRequest requests the application server to validate the join-request and return an encrypted join-accept.
	JoinRequest(ctx context.Context, in *JoinRequestRequest, opts ...grpc.CallOption) (*JoinRequestResponse, error)
	// HandleDataUp publishes data received from an end-device.
	HandleDataUp(ctx context.Context, in *HandleDataUpRequest, opts ...grpc.CallOption) (*HandleDataUpResponse, error)
	// GetDataDown gets data from the downlink queue.
	GetDataDown(ctx context.Context, in *GetDataDownRequest, opts ...grpc.CallOption) (*GetDataDownResponse, error)
	// HandleDataDownACK publishes a data-down ack response.
	HandleDataDownACK(ctx context.Context, in *HandleDataDownACKRequest, opts ...grpc.CallOption) (*HandleDataDownACKResponse, error)
	// HandleError publishes an error message.
	HandleError(ctx context.Context, in *HandleErrorRequest, opts ...grpc.CallOption) (*HandleErrorResponse, error)
}

type applicationServerClient struct {
	cc *grpc.ClientConn
}

func NewApplicationServerClient(cc *grpc.ClientConn) ApplicationServerClient {
	return &applicationServerClient{cc}
}

func (c *applicationServerClient) JoinRequest(ctx context.Context, in *JoinRequestRequest, opts ...grpc.CallOption) (*JoinRequestResponse, error) {
	out := new(JoinRequestResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/JoinRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerClient) HandleDataUp(ctx context.Context, in *HandleDataUpRequest, opts ...grpc.CallOption) (*HandleDataUpResponse, error) {
	out := new(HandleDataUpResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/HandleDataUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerClient) GetDataDown(ctx context.Context, in *GetDataDownRequest, opts ...grpc.CallOption) (*GetDataDownResponse, error) {
	out := new(GetDataDownResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/GetDataDown", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerClient) HandleDataDownACK(ctx context.Context, in *HandleDataDownACKRequest, opts ...grpc.CallOption) (*HandleDataDownACKResponse, error) {
	out := new(HandleDataDownACKResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/HandleDataDownACK", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerClient) HandleError(ctx context.Context, in *HandleErrorRequest, opts ...grpc.CallOption) (*HandleErrorResponse, error) {
	out := new(HandleErrorResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/HandleError", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApplicationServer service

type ApplicationServerServer interface {
	// JoinRequest requests the application server to validate the join-request and return an encrypted join-accept.
	JoinRequest(context.Context, *JoinRequestRequest) (*JoinRequestResponse, error)
	// HandleDataUp publishes data received from an end-device.
	HandleDataUp(context.Context, *HandleDataUpRequest) (*HandleDataUpResponse, error)
	// GetDataDown gets data from the downlink queue.
	GetDataDown(context.Context, *GetDataDownRequest) (*GetDataDownResponse, error)
	// HandleDataDownACK publishes a data-down ack response.
	HandleDataDownACK(context.Context, *HandleDataDownACKRequest) (*HandleDataDownACKResponse, error)
	// HandleError publishes an error message.
	HandleError(context.Context, *HandleErrorRequest) (*HandleErrorResponse, error)
}

func RegisterApplicationServerServer(s *grpc.Server, srv ApplicationServerServer) {
	s.RegisterService(&_ApplicationServer_serviceDesc, srv)
}

func _ApplicationServer_JoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).JoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/JoinRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).JoinRequest(ctx, req.(*JoinRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServer_HandleDataUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleDataUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).HandleDataUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/HandleDataUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).HandleDataUp(ctx, req.(*HandleDataUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServer_GetDataDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).GetDataDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/GetDataDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).GetDataDown(ctx, req.(*GetDataDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServer_HandleDataDownACK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleDataDownACKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).HandleDataDownACK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/HandleDataDownACK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).HandleDataDownACK(ctx, req.(*HandleDataDownACKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServer_HandleError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).HandleError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/HandleError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).HandleError(ctx, req.(*HandleErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApplicationServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "as.ApplicationServer",
	HandlerType: (*ApplicationServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinRequest",
			Handler:    _ApplicationServer_JoinRequest_Handler,
		},
		{
			MethodName: "HandleDataUp",
			Handler:    _ApplicationServer_HandleDataUp_Handler,
		},
		{
			MethodName: "GetDataDown",
			Handler:    _ApplicationServer_GetDataDown_Handler,
		},
		{
			MethodName: "HandleDataDownACK",
			Handler:    _ApplicationServer_HandleDataDownACK_Handler,
		},
		{
			MethodName: "HandleError",
			Handler:    _ApplicationServer_HandleError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "as.proto",
}

func init() { proto.RegisterFile("as.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 922 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x51, 0x6f, 0x1b, 0x45,
	0x10, 0xce, 0xd9, 0xae, 0x7d, 0x1e, 0x3b, 0xc1, 0xdd, 0x94, 0xf4, 0x30, 0x06, 0x99, 0x7b, 0x40,
	0x51, 0x1f, 0x22, 0xd5, 0xfc, 0x81, 0x5a, 0x76, 0x52, 0x4c, 0x69, 0x1b, 0x6d, 0x1c, 0x35, 0x4f,
	0x54, 0x1b, 0xef, 0xba, 0x3d, 0x71, 0xde, 0x3d, 0xf6, 0x36, 0x89, 0x8d, 0x00, 0xf1, 0xc4, 0x9f,
	0xe2, 0x9d, 0x17, 0xfe, 0x0d, 0xbf, 0x00, 0xcd, 0xee, 0x9e, 0x7d, 0xc6, 0x41, 0x42, 0x15, 0x4f,
	0xd9, 0xef, 0x9b, 0xf1, 0x7e, 0x33, 0xdf, 0xcc, 0x9e, 0x02, 0x21, 0xcb, 0x4f, 0x32, 0xad, 0x8c,
	0x22, 0x15, 0x96, 0xc7, 0xbf, 0x05, 0x10, 0x8e, 0x99, 0x61, 0x94, 0x19, 0x41, 0x3e, 0x07, 0x58,
	0x28, 0x7e, 0x93, 0x32, 0x93, 0x28, 0x19, 0x05, 0xfd, 0xe0, 0xb8, 0x49, 0x4b, 0x0c, 0xe9, 0x41,
	0xf3, 0x9a, 0x49, 0xfe, 0x26, 0xe1, 0xe6, 0x7d, 0x54, 0xe9, 0x07, 0xc7, 0xfb, 0x74, 0x43, 0x90,
	0x18, 0xda, 0x79, 0xa6, 0x05, 0xe3, 0x67, 0x6c, 0x66, 0x94, 0x8e, 0xaa, 0x36, 0x61, 0x8b, 0x23,
	0x11, 0x34, 0xae, 0x13, 0xa3, 0x99, 0x11, 0x51, 0xcd, 0x86, 0x0b, 0x18, 0xff, 0x11, 0x40, 0x9d,
	0x5e, 0x4d, 0xe4, 0x5c, 0x91, 0x0e, 0x54, 0x17, 0x6c, 0x66, 0xf5, 0xdb, 0x14, 0x8f, 0x84, 0x40,
	0xcd, 0x24, 0x0b, 0x61, 0x35, 0x9b, 0xd4, 0x9e, 0x91, 0xd3, 0x79, 0x9e, 0x58, 0x99, 0x07, 0xd4,
	0x9e, 0xf1, 0xfa, 0x54, 0x51, 0x76, 0xf1, 0x8a, 0xda, 0xeb, 0x03, 0x5a, 0x40, 0xcc, 0x96, 0x6c,
	0x21, 0xa2, 0x07, 0xee, 0x06, 0x3c, 0x93, 0x2e, 0x84, 0xd8, 0x98, 0xb9, 0xe1, 0x22, 0xaa, 0xdb,
	0xf4, 0x35, 0xc6, 0x56, 0x53, 0x25, 0xdf, 0xb9, 0x60, 0xc3, 0x06, 0x37, 0x04, 0xfe, 0x92, 0xa5,
	0xfe, 0x97, 0xa1, 0xfb, 0x65, 0x81, 0xe3, 0x5f, 0xa0, 0x3e, 0x75, 0x7d, 0xf4, 0xa0, 0x39, 0xd7,
	0xe2, 0x87, 0x1b, 0x21, 0x67, 0x2b, 0xdb, 0x4d, 0x95, 0x6e, 0x08, 0x72, 0x0c, 0x21, 0xf7, 0xc6,
	0xdb, 0xbe, 0x5a, 0x83, 0xf6, 0x09, 0xcb, 0x4f, 0x8a, 0x61, 0xd0, 0x75, 0x14, 0xfd, 0x60, 0xdc,
	0xf9, 0x19, 0x52, 0x3c, 0xa2, 0xfe, 0x4c, 0x71, 0x41, 0x0b, 0x1f, 0x9b, 0x74, 0x8d, 0xe3, 0x9f,
	0x80, 0x7c, 0xa3, 0x12, 0x49, 0x51, 0x27, 0x37, 0xfe, 0x0f, 0x8e, 0x36, 0x7b, 0xbf, 0x3a, 0x67,
	0xab, 0x54, 0x31, 0xee, 0xad, 0x2d, 0x31, 0xe8, 0x1c, 0x17, 0xb7, 0x43, 0xce, 0xb5, 0x2d, 0xa6,
	0x4d, 0x0b, 0x48, 0x1e, 0xc1, 0x03, 0x29, 0xcc, 0x64, 0x6c, 0xf5, 0xdb, 0xd4, 0x01, 0x72, 0x04,
	0xf5, 0xd9, 0xd9, 0xb7, 0x49, 0x6e, 0xa2, 0x5a, 0xbf, 0x7a, 0xbc, 0x4f, 0x3d, 0x8a, 0x7f, 0xaf,
	0xc0, 0xe1, 0x96, 0x7c, 0x9e, 0x29, 0x99, 0x8b, 0xff, 0xa2, 0x2f, 0xef, 0xbe, 0xbf, 0x78, 0x21,
	0x56, 0x85, 0xbe, 0x87, 0x18, 0xd1, 0xcb, 0xb1, 0x48, 0xd9, 0xca, 0x6f, 0x54, 0x01, 0x49, 0x1f,
	0x5a, 0x7a, 0xf9, 0x74, 0x4c, 0x5f, 0xcf, 0xe7, 0xb9, 0x30, 0x7e, 0xa1, 0xca, 0x14, 0x7a, 0xac,
	0x97, 0x6f, 0x12, 0xc9, 0xd5, 0x9d, 0x9d, 0xf0, 0x81, 0xf3, 0x98, 0x5e, 0x39, 0x8e, 0xae, 0xa3,
	0xd8, 0xa5, 0x5e, 0x0e, 0xc6, 0xd4, 0xce, 0x7a, 0x9f, 0x3a, 0x80, 0x13, 0xd4, 0x22, 0x65, 0xcb,
	0xb3, 0x91, 0x34, 0x76, 0xd0, 0x21, 0xdd, 0x10, 0xa8, 0xcf, 0xb8, 0x9e, 0x48, 0x23, 0xf4, 0x2d,
	0x4b, 0xa3, 0xa6, 0xd3, 0x2f, 0x51, 0xe4, 0x04, 0x48, 0x22, 0x73, 0xc3, 0x52, 0xf7, 0x80, 0x5e,
	0x32, 0xfd, 0x2e, 0x91, 0x11, 0xd8, 0x8d, 0xb9, 0x27, 0x12, 0xff, 0x19, 0xc0, 0xe1, 0xd7, 0x4c,
	0xf2, 0x54, 0xe0, 0x1a, 0x5c, 0x66, 0xc5, 0xf4, 0x8e, 0xa0, 0xce, 0xc5, 0xed, 0xe9, 0xe5, 0xc4,
	0x3b, 0xe7, 0x11, 0xf2, 0x2c, 0xcb, 0x90, 0x77, 0xa6, 0x79, 0x84, 0xdb, 0x3e, 0xc7, 0x92, 0x9d,
	0x61, 0xf6, 0x8c, 0x1d, 0xce, 0xcf, 0x95, 0x2e, 0x7c, 0x72, 0x00, 0x33, 0x71, 0xcf, 0xec, 0xbb,
	0x68, 0x53, 0x7b, 0x26, 0x31, 0xd4, 0xcd, 0x12, 0x37, 0xd8, 0x7a, 0xd6, 0x1a, 0x00, 0x7a, 0xe6,
	0x76, 0x9a, 0xfa, 0x08, 0xe6, 0x68, 0x97, 0xd3, 0xe8, 0x57, 0x8b, 0x1c, 0xea, 0x73, 0x5c, 0x24,
	0xfe, 0x35, 0x00, 0xf2, 0x5c, 0x18, 0x6c, 0x65, 0xac, 0xee, 0xe4, 0x87, 0x36, 0xf3, 0x25, 0x1c,
	0x2c, 0xd8, 0xd2, 0x2f, 0xca, 0x45, 0xf2, 0xa3, 0xf0, 0x6d, 0xfd, 0x83, 0x5d, 0x37, 0x5d, 0xdb,
	0x34, 0x1d, 0xaf, 0xe0, 0x70, 0xab, 0x02, 0xbf, 0x8d, 0x45, 0xd7, 0x41, 0xa9, 0xeb, 0x1e, 0x34,
	0x67, 0x4a, 0xce, 0x13, 0xbd, 0x10, 0xdc, 0x56, 0x10, 0xd2, 0x0d, 0xb1, 0x71, 0xaf, 0x5a, 0x76,
	0xaf, 0x0b, 0xe1, 0x42, 0x69, 0x3b, 0x2c, 0x2b, 0x1b, 0xd2, 0x35, 0x8e, 0x8f, 0xe0, 0xd1, 0xf6,
	0x28, 0x9d, 0x76, 0xfc, 0x1d, 0x44, 0x1b, 0x1e, 0xab, 0x1a, 0x8e, 0x5e, 0xfc, 0x8f, 0x73, 0x8e,
	0x3f, 0x85, 0x4f, 0xee, 0xb9, 0xdf, 0x8b, 0xff, 0x0c, 0xc4, 0x05, 0x4f, 0xb5, 0x56, 0xfa, 0x43,
	0x65, 0xbf, 0x80, 0x9a, 0x59, 0x65, 0x6e, 0x0e, 0x07, 0x83, 0x7d, 0x1c, 0xbd, 0xbd, 0x6f, 0xba,
	0xca, 0x04, 0xb5, 0x21, 0xf4, 0x4b, 0x20, 0xe5, 0x3f, 0x4f, 0x0e, 0xc4, 0x1f, 0x17, 0xeb, 0xed,
	0xe5, 0x5d, 0x55, 0x4f, 0x7a, 0x10, 0x16, 0x4f, 0x92, 0x34, 0xa0, 0x4a, 0xaf, 0x9e, 0x76, 0xf6,
	0xdc, 0x61, 0xd0, 0x09, 0x9e, 0x9c, 0x42, 0x73, 0x7d, 0x3b, 0x69, 0x41, 0xe3, 0xb9, 0x90, 0x42,
	0x27, 0xb3, 0xce, 0x1e, 0x09, 0xa1, 0xf6, 0x7a, 0x3a, 0x1c, 0x76, 0x02, 0xd2, 0x81, 0xf6, 0x78,
	0x38, 0x1d, 0xbe, 0xbd, 0x3c, 0x7f, 0x7b, 0x36, 0x7a, 0x35, 0xed, 0x54, 0xc8, 0x47, 0xd0, 0x2a,
	0x98, 0x97, 0x93, 0x51, 0xa7, 0x3a, 0xf8, 0xab, 0x02, 0x0f, 0x87, 0x59, 0x96, 0x26, 0x33, 0xfb,
	0xe2, 0x2e, 0x84, 0xbe, 0x15, 0x9a, 0x3c, 0x83, 0x56, 0xe9, 0x73, 0x45, 0x8e, 0xb0, 0x97, 0xdd,
	0xcf, 0x67, 0xf7, 0xf1, 0x0e, 0xef, 0x0d, 0xdd, 0x23, 0x23, 0x68, 0x97, 0xe7, 0x4c, 0x6c, 0xea,
	0x3d, 0x8f, 0xb8, 0x1b, 0xed, 0x06, 0xd6, 0x97, 0x3c, 0x83, 0x56, 0x69, 0x4f, 0x5d, 0x19, 0xbb,
	0x4f, 0xc7, 0x95, 0x71, 0xcf, 0x42, 0xc7, 0x7b, 0x84, 0xc2, 0xc3, 0x9d, 0xb1, 0x93, 0xde, 0xb6,
	0xe4, 0xf6, 0xb6, 0x75, 0x3f, 0xfb, 0x97, 0x68, 0xb9, 0xaa, 0xd2, 0xb8, 0x5c, 0x55, 0xbb, 0xeb,
	0xd3, 0x7d, 0xbc, 0xc3, 0x17, 0x37, 0x5c, 0xd7, 0xed, 0x7f, 0x1a, 0x5f, 0xfd, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xb1, 0x87, 0x2f, 0x34, 0x75, 0x08, 0x00, 0x00,
}
