// Code generated by protoc-gen-go.
// source: as.proto
// DO NOT EDIT!

/*
Package as is a generated protocol buffer package.

It is generated from these files:
	as.proto

It has these top-level messages:
	DataRate
	RXInfo
	JoinRequestRequest
	JoinRequestResponse
	PublishDataUpRequest
	PublishDataUpResponse
	PublishDataDownACKRequest
	PublishDataDownACKResponse
	PublishErrorRequest
	PublishErrorResponse
*/
package as

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RXWindow int32

const (
	RXWindow_RX1 RXWindow = 0
	RXWindow_RX2 RXWindow = 1
)

var RXWindow_name = map[int32]string{
	0: "RX1",
	1: "RX2",
}
var RXWindow_value = map[string]int32{
	"RX1": 0,
	"RX2": 1,
}

func (x RXWindow) String() string {
	return proto.EnumName(RXWindow_name, int32(x))
}
func (RXWindow) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DataRate struct {
	SpreadFactor uint32 `protobuf:"varint,1,opt,name=spreadFactor" json:"spreadFactor,omitempty"`
	BandWidth    uint32 `protobuf:"varint,2,opt,name=bandWidth" json:"bandWidth,omitempty"`
	Bitrate      uint32 `protobuf:"varint,3,opt,name=bitrate" json:"bitrate,omitempty"`
	Modulation   string `protobuf:"bytes,4,opt,name=modulation" json:"modulation,omitempty"`
}

func (m *DataRate) Reset()                    { *m = DataRate{} }
func (m *DataRate) String() string            { return proto.CompactTextString(m) }
func (*DataRate) ProtoMessage()               {}
func (*DataRate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RXInfo struct {
	Mac       []byte    `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Time      string    `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Frequency int64     `protobuf:"varint,3,opt,name=frequency" json:"frequency,omitempty"`
	DataRate  *DataRate `protobuf:"bytes,4,opt,name=dataRate" json:"dataRate,omitempty"`
	CodeRate  string    `protobuf:"bytes,5,opt,name=codeRate" json:"codeRate,omitempty"`
	Rssi      int32     `protobuf:"varint,6,opt,name=rssi" json:"rssi,omitempty"`
	LoRaSNR   float64   `protobuf:"fixed64,7,opt,name=loRaSNR" json:"loRaSNR,omitempty"`
}

func (m *RXInfo) Reset()                    { *m = RXInfo{} }
func (m *RXInfo) String() string            { return proto.CompactTextString(m) }
func (*RXInfo) ProtoMessage()               {}
func (*RXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RXInfo) GetDataRate() *DataRate {
	if m != nil {
		return m.DataRate
	}
	return nil
}

type JoinRequestRequest struct {
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phyPayload,proto3" json:"phyPayload,omitempty"`
	DevAddr    []byte `protobuf:"bytes,2,opt,name=devAddr,proto3" json:"devAddr,omitempty"`
}

func (m *JoinRequestRequest) Reset()                    { *m = JoinRequestRequest{} }
func (m *JoinRequestRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequestRequest) ProtoMessage()               {}
func (*JoinRequestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type JoinRequestResponse struct {
	PhyPayload  []byte   `protobuf:"bytes,1,opt,name=phyPayload,proto3" json:"phyPayload,omitempty"`
	NwkSKey     []byte   `protobuf:"bytes,2,opt,name=nwkSKey,proto3" json:"nwkSKey,omitempty"`
	AppEUI      []byte   `protobuf:"bytes,3,opt,name=appEUI,proto3" json:"appEUI,omitempty"`
	DevEUI      []byte   `protobuf:"bytes,4,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	RxDelay     uint32   `protobuf:"varint,5,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset uint32   `protobuf:"varint,6,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	CFList      []uint32 `protobuf:"varint,7,rep,packed,name=cFList" json:"cFList,omitempty"`
	RxWindow    RXWindow `protobuf:"varint,8,opt,name=rxWindow,enum=as.RXWindow" json:"rxWindow,omitempty"`
	Rx2DR       uint32   `protobuf:"varint,9,opt,name=rx2DR" json:"rx2DR,omitempty"`
}

func (m *JoinRequestResponse) Reset()                    { *m = JoinRequestResponse{} }
func (m *JoinRequestResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinRequestResponse) ProtoMessage()               {}
func (*JoinRequestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PublishDataUpRequest struct {
	DevEUI []byte    `protobuf:"bytes,1,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	FCnt   uint32    `protobuf:"varint,2,opt,name=fCnt" json:"fCnt,omitempty"`
	Data   []byte    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	RxInfo []*RXInfo `protobuf:"bytes,4,rep,name=rxInfo" json:"rxInfo,omitempty"`
}

func (m *PublishDataUpRequest) Reset()                    { *m = PublishDataUpRequest{} }
func (m *PublishDataUpRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishDataUpRequest) ProtoMessage()               {}
func (*PublishDataUpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PublishDataUpRequest) GetRxInfo() []*RXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

type PublishDataUpResponse struct {
}

func (m *PublishDataUpResponse) Reset()                    { *m = PublishDataUpResponse{} }
func (m *PublishDataUpResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishDataUpResponse) ProtoMessage()               {}
func (*PublishDataUpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type PublishDataDownACKRequest struct {
	Reference int64  `protobuf:"varint,1,opt,name=reference" json:"reference,omitempty"`
	DevEUI    []byte `protobuf:"bytes,2,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
}

func (m *PublishDataDownACKRequest) Reset()                    { *m = PublishDataDownACKRequest{} }
func (m *PublishDataDownACKRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishDataDownACKRequest) ProtoMessage()               {}
func (*PublishDataDownACKRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type PublishDataDownACKResponse struct {
}

func (m *PublishDataDownACKResponse) Reset()                    { *m = PublishDataDownACKResponse{} }
func (m *PublishDataDownACKResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishDataDownACKResponse) ProtoMessage()               {}
func (*PublishDataDownACKResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type PublishErrorRequest struct {
	Reference int64  `protobuf:"varint,1,opt,name=reference" json:"reference,omitempty"`
	DevEUI    []byte `protobuf:"bytes,2,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *PublishErrorRequest) Reset()                    { *m = PublishErrorRequest{} }
func (m *PublishErrorRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishErrorRequest) ProtoMessage()               {}
func (*PublishErrorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type PublishErrorResponse struct {
}

func (m *PublishErrorResponse) Reset()                    { *m = PublishErrorResponse{} }
func (m *PublishErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishErrorResponse) ProtoMessage()               {}
func (*PublishErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*DataRate)(nil), "as.DataRate")
	proto.RegisterType((*RXInfo)(nil), "as.RXInfo")
	proto.RegisterType((*JoinRequestRequest)(nil), "as.JoinRequestRequest")
	proto.RegisterType((*JoinRequestResponse)(nil), "as.JoinRequestResponse")
	proto.RegisterType((*PublishDataUpRequest)(nil), "as.PublishDataUpRequest")
	proto.RegisterType((*PublishDataUpResponse)(nil), "as.PublishDataUpResponse")
	proto.RegisterType((*PublishDataDownACKRequest)(nil), "as.PublishDataDownACKRequest")
	proto.RegisterType((*PublishDataDownACKResponse)(nil), "as.PublishDataDownACKResponse")
	proto.RegisterType((*PublishErrorRequest)(nil), "as.PublishErrorRequest")
	proto.RegisterType((*PublishErrorResponse)(nil), "as.PublishErrorResponse")
	proto.RegisterEnum("as.RXWindow", RXWindow_name, RXWindow_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ApplicationServer service

type ApplicationServerClient interface {
	// JoinRequest requests the application server to validate the join-request and return an encrypted join-accept.
	JoinRequest(ctx context.Context, in *JoinRequestRequest, opts ...grpc.CallOption) (*JoinRequestResponse, error)
	// PublishDataUp publishes data received from an end-device.
	PublishDataUp(ctx context.Context, in *PublishDataUpRequest, opts ...grpc.CallOption) (*PublishDataUpResponse, error)
	// PublishDataDownACK publishes a data-down ack response.
	PublishDataDownACK(ctx context.Context, in *PublishDataDownACKRequest, opts ...grpc.CallOption) (*PublishDataDownACKResponse, error)
	// PublishError publishes an error message.
	PublishError(ctx context.Context, in *PublishErrorRequest, opts ...grpc.CallOption) (*PublishErrorResponse, error)
}

type applicationServerClient struct {
	cc *grpc.ClientConn
}

func NewApplicationServerClient(cc *grpc.ClientConn) ApplicationServerClient {
	return &applicationServerClient{cc}
}

func (c *applicationServerClient) JoinRequest(ctx context.Context, in *JoinRequestRequest, opts ...grpc.CallOption) (*JoinRequestResponse, error) {
	out := new(JoinRequestResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/JoinRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerClient) PublishDataUp(ctx context.Context, in *PublishDataUpRequest, opts ...grpc.CallOption) (*PublishDataUpResponse, error) {
	out := new(PublishDataUpResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/PublishDataUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerClient) PublishDataDownACK(ctx context.Context, in *PublishDataDownACKRequest, opts ...grpc.CallOption) (*PublishDataDownACKResponse, error) {
	out := new(PublishDataDownACKResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/PublishDataDownACK", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerClient) PublishError(ctx context.Context, in *PublishErrorRequest, opts ...grpc.CallOption) (*PublishErrorResponse, error) {
	out := new(PublishErrorResponse)
	err := grpc.Invoke(ctx, "/as.ApplicationServer/PublishError", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApplicationServer service

type ApplicationServerServer interface {
	// JoinRequest requests the application server to validate the join-request and return an encrypted join-accept.
	JoinRequest(context.Context, *JoinRequestRequest) (*JoinRequestResponse, error)
	// PublishDataUp publishes data received from an end-device.
	PublishDataUp(context.Context, *PublishDataUpRequest) (*PublishDataUpResponse, error)
	// PublishDataDownACK publishes a data-down ack response.
	PublishDataDownACK(context.Context, *PublishDataDownACKRequest) (*PublishDataDownACKResponse, error)
	// PublishError publishes an error message.
	PublishError(context.Context, *PublishErrorRequest) (*PublishErrorResponse, error)
}

func RegisterApplicationServerServer(s *grpc.Server, srv ApplicationServerServer) {
	s.RegisterService(&_ApplicationServer_serviceDesc, srv)
}

func _ApplicationServer_JoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).JoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/JoinRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).JoinRequest(ctx, req.(*JoinRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServer_PublishDataUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishDataUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).PublishDataUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/PublishDataUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).PublishDataUp(ctx, req.(*PublishDataUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServer_PublishDataDownACK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishDataDownACKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).PublishDataDownACK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/PublishDataDownACK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).PublishDataDownACK(ctx, req.(*PublishDataDownACKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServer_PublishError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServer).PublishError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as.ApplicationServer/PublishError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServer).PublishError(ctx, req.(*PublishErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApplicationServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "as.ApplicationServer",
	HandlerType: (*ApplicationServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinRequest",
			Handler:    _ApplicationServer_JoinRequest_Handler,
		},
		{
			MethodName: "PublishDataUp",
			Handler:    _ApplicationServer_PublishDataUp_Handler,
		},
		{
			MethodName: "PublishDataDownACK",
			Handler:    _ApplicationServer_PublishDataDownACK_Handler,
		},
		{
			MethodName: "PublishError",
			Handler:    _ApplicationServer_PublishError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("as.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x4e, 0x1b, 0x3d,
	0x10, 0x65, 0x93, 0x90, 0x9f, 0x49, 0xf2, 0x89, 0xcf, 0x50, 0x30, 0x51, 0x8a, 0x56, 0x7b, 0xb5,
	0xea, 0x05, 0x12, 0xe9, 0x0b, 0x14, 0x11, 0x90, 0x28, 0x15, 0xa5, 0x83, 0x10, 0xdc, 0x3a, 0xbb,
	0x4e, 0x59, 0x35, 0x59, 0x6f, 0x6d, 0x03, 0x49, 0x1f, 0xa0, 0x2f, 0xd0, 0xa7, 0xe9, 0x5d, 0x1f,
	0xad, 0xb2, 0xd7, 0x9b, 0x6c, 0x08, 0x95, 0x2a, 0xf5, 0x2a, 0x73, 0xce, 0x78, 0xcf, 0xcc, 0x9c,
	0xb1, 0x03, 0x4d, 0xa6, 0x0e, 0x33, 0x29, 0xb4, 0x20, 0x15, 0xa6, 0x82, 0xef, 0x1e, 0x34, 0x87,
	0x4c, 0x33, 0x64, 0x9a, 0x93, 0x00, 0x3a, 0x2a, 0x93, 0x9c, 0xc5, 0x67, 0x2c, 0xd2, 0x42, 0x52,
	0xcf, 0xf7, 0xc2, 0x2e, 0xae, 0x70, 0xa4, 0x0f, 0xad, 0x11, 0x4b, 0xe3, 0xdb, 0x24, 0xd6, 0xf7,
	0xb4, 0x62, 0x0f, 0x2c, 0x09, 0x42, 0xa1, 0x31, 0x4a, 0xb4, 0x64, 0x9a, 0xd3, 0xaa, 0xcd, 0x15,
	0x90, 0x1c, 0x00, 0x4c, 0x45, 0xfc, 0x30, 0x61, 0x3a, 0x11, 0x29, 0xad, 0xf9, 0x5e, 0xd8, 0xc2,
	0x12, 0x13, 0xfc, 0xf2, 0xa0, 0x8e, 0x77, 0xe7, 0xe9, 0x58, 0x90, 0x2d, 0xa8, 0x4e, 0x59, 0x64,
	0xab, 0x77, 0xd0, 0x84, 0x84, 0x40, 0x4d, 0x27, 0x53, 0x6e, 0xeb, 0xb5, 0xd0, 0xc6, 0xa6, 0x91,
	0xb1, 0xe4, 0x5f, 0x1f, 0x78, 0x1a, 0xcd, 0x6d, 0xb1, 0x2a, 0x2e, 0x09, 0x12, 0x42, 0x33, 0x76,
	0x63, 0xd9, 0x62, 0xed, 0x41, 0xe7, 0x90, 0xa9, 0xc3, 0x62, 0x54, 0x5c, 0x64, 0x49, 0x0f, 0x9a,
	0x91, 0x88, 0xb9, 0x3d, 0xb9, 0x69, 0xf5, 0x17, 0xd8, 0xd4, 0x95, 0x4a, 0x25, 0xb4, 0xee, 0x7b,
	0xe1, 0x26, 0xda, 0xd8, 0x8c, 0x38, 0x11, 0xc8, 0xae, 0x2f, 0x91, 0x36, 0x7c, 0x2f, 0xf4, 0xb0,
	0x80, 0xc1, 0x25, 0x90, 0xf7, 0x22, 0x49, 0xd1, 0xf4, 0xa0, 0xb4, 0xfb, 0x31, 0x83, 0x67, 0xf7,
	0xf3, 0x2b, 0x36, 0x9f, 0x08, 0x16, 0xbb, 0xa1, 0x4a, 0x8c, 0xd1, 0x8b, 0xf9, 0xe3, 0x71, 0x1c,
	0x4b, 0x3b, 0x5e, 0x07, 0x0b, 0x18, 0xfc, 0xa8, 0xc0, 0xf6, 0x8a, 0xa0, 0xca, 0x44, 0xaa, 0xf8,
	0xdf, 0x28, 0xa6, 0x4f, 0x5f, 0xae, 0x2f, 0xf8, 0xbc, 0x50, 0x74, 0x90, 0xec, 0x42, 0x9d, 0x65,
	0xd9, 0xe9, 0xcd, 0xb9, 0x35, 0xac, 0x83, 0x0e, 0x19, 0x3e, 0xe6, 0x8f, 0x86, 0xaf, 0xe5, 0x7c,
	0x8e, 0x8c, 0x92, 0x9c, 0x0d, 0xf9, 0x84, 0xcd, 0xad, 0x35, 0x5d, 0x2c, 0x20, 0xf1, 0xa1, 0x2d,
	0x67, 0x47, 0x43, 0xfc, 0x38, 0x1e, 0x2b, 0xae, 0xad, 0x41, 0x5d, 0x2c, 0x53, 0x46, 0x33, 0x3a,
	0xfb, 0x90, 0x28, 0x4d, 0x1b, 0x7e, 0x35, 0xec, 0xa2, 0x43, 0x66, 0x33, 0x72, 0x76, 0x9b, 0xa4,
	0xb1, 0x78, 0xa2, 0x4d, 0xdf, 0x0b, 0xff, 0xcb, 0x37, 0x83, 0x77, 0x39, 0x87, 0x8b, 0x2c, 0xd9,
	0x81, 0x4d, 0x39, 0x1b, 0x0c, 0x91, 0xb6, 0xac, 0x7a, 0x0e, 0x82, 0x6f, 0xb0, 0x73, 0xf5, 0x30,
	0x9a, 0x24, 0xea, 0xde, 0x2c, 0xf3, 0x26, 0x2b, 0x7c, 0x5e, 0xce, 0xe0, 0xad, 0xcc, 0x40, 0xa0,
	0x36, 0x3e, 0x49, 0xb5, 0xbb, 0xab, 0x36, 0x36, 0x9c, 0xd9, 0xbf, 0x73, 0xc1, 0xc6, 0x24, 0x80,
	0xba, 0x9c, 0x99, 0xfb, 0x47, 0x6b, 0x7e, 0x35, 0x6c, 0x0f, 0x20, 0xef, 0xca, 0x30, 0xe8, 0x32,
	0xc1, 0x1e, 0xbc, 0x7a, 0x56, 0x3b, 0x5f, 0x49, 0xf0, 0x09, 0xf6, 0x4b, 0x89, 0xa1, 0x78, 0x4a,
	0x8f, 0x4f, 0x2e, 0x8a, 0xce, 0xfa, 0xd0, 0x92, 0x7c, 0xcc, 0x25, 0x4f, 0x23, 0x6e, 0x9b, 0xab,
	0xe2, 0x92, 0x28, 0xf5, 0x5d, 0x29, 0xf7, 0x1d, 0xf4, 0xa1, 0xf7, 0x92, 0xa4, 0x2b, 0xc8, 0x61,
	0xdb, 0x65, 0x4f, 0xa5, 0x14, 0xf2, 0x9f, 0x4a, 0x99, 0x35, 0x4f, 0xb9, 0x52, 0xec, 0x73, 0xfe,
	0x6a, 0x5b, 0x58, 0xc0, 0x60, 0x77, 0x61, 0xb6, 0x2b, 0x93, 0x97, 0x7f, 0xd3, 0x87, 0x66, 0xb1,
	0x30, 0xd2, 0x80, 0x2a, 0xde, 0x1d, 0x6d, 0x6d, 0xe4, 0xc1, 0x60, 0xcb, 0x1b, 0xfc, 0xac, 0xc0,
	0xff, 0xc7, 0x59, 0x36, 0x49, 0x22, 0xfb, 0xb6, 0xaf, 0xb9, 0x7c, 0xe4, 0x92, 0xbc, 0x83, 0x76,
	0xe9, 0x36, 0x93, 0x5d, 0xe3, 0xef, 0xfa, 0x7b, 0xe9, 0xed, 0xad, 0xf1, 0x6e, 0xe4, 0x0d, 0x72,
	0x06, 0xdd, 0x15, 0xfb, 0x09, 0x35, 0x67, 0x5f, 0xba, 0x0d, 0xbd, 0xfd, 0x17, 0x32, 0x0b, 0x9d,
	0x1b, 0x20, 0xeb, 0xd6, 0x92, 0xd7, 0xcf, 0x3e, 0x59, 0xdd, 0x62, 0xef, 0xe0, 0x4f, 0xe9, 0x85,
	0xec, 0x09, 0x74, 0xca, 0x66, 0x91, 0xbd, 0xd2, 0x17, 0xe5, 0x2d, 0xf5, 0xe8, 0x7a, 0xa2, 0x10,
	0x19, 0xd5, 0xed, 0x7f, 0xf3, 0xdb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68, 0xc3, 0x3d, 0x3f,
	0xa7, 0x05, 0x00, 0x00,
}
