// Code generated by protoc-gen-go.
// source: nc.proto
// DO NOT EDIT!

/*
Package nc is a generated protocol buffer package.

It is generated from these files:
	nc.proto

It has these top-level messages:
	DataRate
	RXInfo
	TXInfo
	HandleRXInfoRequest
	HandleRXInfoResponse
	HandleDataUpMACCommandRequest
	HandleDataUpMACCommandResponse
	HandleErrorRequest
	HandleErrorResponse
*/
package nc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataRate struct {
	Modulation   string `protobuf:"bytes,1,opt,name=modulation" json:"modulation,omitempty"`
	BandWidth    uint32 `protobuf:"varint,2,opt,name=bandWidth" json:"bandWidth,omitempty"`
	SpreadFactor uint32 `protobuf:"varint,3,opt,name=spreadFactor" json:"spreadFactor,omitempty"`
	Bitrate      uint32 `protobuf:"varint,4,opt,name=bitrate" json:"bitrate,omitempty"`
}

func (m *DataRate) Reset()                    { *m = DataRate{} }
func (m *DataRate) String() string            { return proto.CompactTextString(m) }
func (*DataRate) ProtoMessage()               {}
func (*DataRate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RXInfo struct {
	Mac     []byte  `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Time    string  `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Rssi    int32   `protobuf:"varint,3,opt,name=rssi" json:"rssi,omitempty"`
	LoRaSNR float64 `protobuf:"fixed64,4,opt,name=loRaSNR" json:"loRaSNR,omitempty"`
}

func (m *RXInfo) Reset()                    { *m = RXInfo{} }
func (m *RXInfo) String() string            { return proto.CompactTextString(m) }
func (*RXInfo) ProtoMessage()               {}
func (*RXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TXInfo struct {
	Frequency int64     `protobuf:"varint,1,opt,name=frequency" json:"frequency,omitempty"`
	DataRate  *DataRate `protobuf:"bytes,2,opt,name=dataRate" json:"dataRate,omitempty"`
	Adr       bool      `protobuf:"varint,3,opt,name=adr" json:"adr,omitempty"`
	CodeRate  string    `protobuf:"bytes,4,opt,name=codeRate" json:"codeRate,omitempty"`
}

func (m *TXInfo) Reset()                    { *m = TXInfo{} }
func (m *TXInfo) String() string            { return proto.CompactTextString(m) }
func (*TXInfo) ProtoMessage()               {}
func (*TXInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TXInfo) GetDataRate() *DataRate {
	if m != nil {
		return m.DataRate
	}
	return nil
}

type HandleRXInfoRequest struct {
	DevEUI []byte    `protobuf:"bytes,1,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	TxInfo *TXInfo   `protobuf:"bytes,2,opt,name=txInfo" json:"txInfo,omitempty"`
	RxInfo []*RXInfo `protobuf:"bytes,3,rep,name=rxInfo" json:"rxInfo,omitempty"`
}

func (m *HandleRXInfoRequest) Reset()                    { *m = HandleRXInfoRequest{} }
func (m *HandleRXInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*HandleRXInfoRequest) ProtoMessage()               {}
func (*HandleRXInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HandleRXInfoRequest) GetTxInfo() *TXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *HandleRXInfoRequest) GetRxInfo() []*RXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

type HandleRXInfoResponse struct {
}

func (m *HandleRXInfoResponse) Reset()                    { *m = HandleRXInfoResponse{} }
func (m *HandleRXInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*HandleRXInfoResponse) ProtoMessage()               {}
func (*HandleRXInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type HandleDataUpMACCommandRequest struct {
	DevEUI     []byte `protobuf:"bytes,1,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	FrmPayload bool   `protobuf:"varint,2,opt,name=frmPayload" json:"frmPayload,omitempty"`
	Data       []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *HandleDataUpMACCommandRequest) Reset()                    { *m = HandleDataUpMACCommandRequest{} }
func (m *HandleDataUpMACCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*HandleDataUpMACCommandRequest) ProtoMessage()               {}
func (*HandleDataUpMACCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type HandleDataUpMACCommandResponse struct {
}

func (m *HandleDataUpMACCommandResponse) Reset()                    { *m = HandleDataUpMACCommandResponse{} }
func (m *HandleDataUpMACCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*HandleDataUpMACCommandResponse) ProtoMessage()               {}
func (*HandleDataUpMACCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type HandleErrorRequest struct {
	DevEUI []byte `protobuf:"bytes,1,opt,name=devEUI,proto3" json:"devEUI,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *HandleErrorRequest) Reset()                    { *m = HandleErrorRequest{} }
func (m *HandleErrorRequest) String() string            { return proto.CompactTextString(m) }
func (*HandleErrorRequest) ProtoMessage()               {}
func (*HandleErrorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type HandleErrorResponse struct {
}

func (m *HandleErrorResponse) Reset()                    { *m = HandleErrorResponse{} }
func (m *HandleErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*HandleErrorResponse) ProtoMessage()               {}
func (*HandleErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*DataRate)(nil), "nc.DataRate")
	proto.RegisterType((*RXInfo)(nil), "nc.RXInfo")
	proto.RegisterType((*TXInfo)(nil), "nc.TXInfo")
	proto.RegisterType((*HandleRXInfoRequest)(nil), "nc.HandleRXInfoRequest")
	proto.RegisterType((*HandleRXInfoResponse)(nil), "nc.HandleRXInfoResponse")
	proto.RegisterType((*HandleDataUpMACCommandRequest)(nil), "nc.HandleDataUpMACCommandRequest")
	proto.RegisterType((*HandleDataUpMACCommandResponse)(nil), "nc.HandleDataUpMACCommandResponse")
	proto.RegisterType((*HandleErrorRequest)(nil), "nc.HandleErrorRequest")
	proto.RegisterType((*HandleErrorResponse)(nil), "nc.HandleErrorResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for NetworkController service

type NetworkControllerClient interface {
	// HandleRXInfo publishes rx related meta-data.
	HandleRXInfo(ctx context.Context, in *HandleRXInfoRequest, opts ...grpc.CallOption) (*HandleRXInfoResponse, error)
	// HandleDataUpMACCommand publishes a mac-command received by an end-device.
	HandleDataUpMACCommand(ctx context.Context, in *HandleDataUpMACCommandRequest, opts ...grpc.CallOption) (*HandleDataUpMACCommandResponse, error)
	// HandleError publishes an error message.
	HandleError(ctx context.Context, in *HandleErrorRequest, opts ...grpc.CallOption) (*HandleErrorResponse, error)
}

type networkControllerClient struct {
	cc *grpc.ClientConn
}

func NewNetworkControllerClient(cc *grpc.ClientConn) NetworkControllerClient {
	return &networkControllerClient{cc}
}

func (c *networkControllerClient) HandleRXInfo(ctx context.Context, in *HandleRXInfoRequest, opts ...grpc.CallOption) (*HandleRXInfoResponse, error) {
	out := new(HandleRXInfoResponse)
	err := grpc.Invoke(ctx, "/nc.NetworkController/HandleRXInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControllerClient) HandleDataUpMACCommand(ctx context.Context, in *HandleDataUpMACCommandRequest, opts ...grpc.CallOption) (*HandleDataUpMACCommandResponse, error) {
	out := new(HandleDataUpMACCommandResponse)
	err := grpc.Invoke(ctx, "/nc.NetworkController/HandleDataUpMACCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControllerClient) HandleError(ctx context.Context, in *HandleErrorRequest, opts ...grpc.CallOption) (*HandleErrorResponse, error) {
	out := new(HandleErrorResponse)
	err := grpc.Invoke(ctx, "/nc.NetworkController/HandleError", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NetworkController service

type NetworkControllerServer interface {
	// HandleRXInfo publishes rx related meta-data.
	HandleRXInfo(context.Context, *HandleRXInfoRequest) (*HandleRXInfoResponse, error)
	// HandleDataUpMACCommand publishes a mac-command received by an end-device.
	HandleDataUpMACCommand(context.Context, *HandleDataUpMACCommandRequest) (*HandleDataUpMACCommandResponse, error)
	// HandleError publishes an error message.
	HandleError(context.Context, *HandleErrorRequest) (*HandleErrorResponse, error)
}

func RegisterNetworkControllerServer(s *grpc.Server, srv NetworkControllerServer) {
	s.RegisterService(&_NetworkController_serviceDesc, srv)
}

func _NetworkController_HandleRXInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRXInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControllerServer).HandleRXInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nc.NetworkController/HandleRXInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControllerServer).HandleRXInfo(ctx, req.(*HandleRXInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkController_HandleDataUpMACCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleDataUpMACCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControllerServer).HandleDataUpMACCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nc.NetworkController/HandleDataUpMACCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControllerServer).HandleDataUpMACCommand(ctx, req.(*HandleDataUpMACCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkController_HandleError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControllerServer).HandleError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nc.NetworkController/HandleError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControllerServer).HandleError(ctx, req.(*HandleErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nc.NetworkController",
	HandlerType: (*NetworkControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleRXInfo",
			Handler:    _NetworkController_HandleRXInfo_Handler,
		},
		{
			MethodName: "HandleDataUpMACCommand",
			Handler:    _NetworkController_HandleDataUpMACCommand_Handler,
		},
		{
			MethodName: "HandleError",
			Handler:    _NetworkController_HandleError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("nc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x6f, 0xd3, 0x30,
	0x14, 0x27, 0xeb, 0x16, 0x92, 0xb7, 0x20, 0xc1, 0x63, 0x74, 0x51, 0x35, 0xaa, 0xe2, 0x53, 0x4f,
	0x3d, 0x8c, 0x7f, 0x00, 0x28, 0x43, 0xec, 0xc0, 0x84, 0x1e, 0x4c, 0x70, 0xe0, 0xe2, 0xc6, 0xae,
	0x88, 0x96, 0xd8, 0xc5, 0x71, 0x81, 0x5d, 0x38, 0xf2, 0x5f, 0x23, 0x21, 0x3b, 0x4e, 0x9b, 0x69,
	0x5f, 0xb7, 0xf7, 0xf1, 0xcb, 0xfb, 0x7d, 0x58, 0x81, 0x44, 0x15, 0xb3, 0x95, 0xd1, 0x56, 0xe3,
	0x8e, 0x2a, 0xd8, 0xdf, 0x08, 0x92, 0xb7, 0xdc, 0x72, 0xe2, 0x56, 0xe2, 0x18, 0xa0, 0xd6, 0x62,
	0x5d, 0x71, 0x5b, 0x6a, 0x95, 0x47, 0x93, 0x68, 0x9a, 0x52, 0x6f, 0x82, 0x47, 0x90, 0x2e, 0xb8,
	0x12, 0x5f, 0x4a, 0x61, 0xbf, 0xe7, 0x3b, 0x93, 0x68, 0xfa, 0x88, 0xb6, 0x03, 0x64, 0x90, 0x35,
	0x2b, 0x23, 0xb9, 0x78, 0xc7, 0x0b, 0xab, 0x4d, 0x3e, 0xf0, 0x80, 0x2b, 0x33, 0xcc, 0xe1, 0xe1,
	0xa2, 0xb4, 0x86, 0x5b, 0x99, 0xef, 0xfa, 0x75, 0xd7, 0xb2, 0x6f, 0x10, 0xd3, 0xd7, 0x53, 0xb5,
	0xd4, 0xf8, 0x18, 0x06, 0x35, 0x2f, 0x3c, 0x7d, 0x46, 0xae, 0x44, 0x84, 0x5d, 0x5b, 0xd6, 0xd2,
	0x53, 0xa6, 0xe4, 0x6b, 0x37, 0x33, 0x4d, 0x53, 0x7a, 0x96, 0x3d, 0xf2, 0xb5, 0xbb, 0x5e, 0x69,
	0xe2, 0x9f, 0xce, 0xc8, 0x5f, 0x8f, 0xa8, 0x6b, 0xd9, 0x1f, 0x88, 0x3f, 0xb7, 0xd7, 0x8f, 0x20,
	0x5d, 0x1a, 0xf9, 0x63, 0x2d, 0x55, 0x71, 0xe9, 0x39, 0x06, 0xb4, 0x1d, 0xe0, 0x14, 0x12, 0x11,
	0xd2, 0xf0, 0x6c, 0xfb, 0xc7, 0xd9, 0x4c, 0x15, 0xb3, 0x2e, 0x21, 0xda, 0x6c, 0x9d, 0x4a, 0x2e,
	0x5a, 0x93, 0x09, 0xb9, 0x12, 0x47, 0x90, 0x14, 0x5a, 0x48, 0xea, 0xcc, 0xa5, 0xb4, 0xe9, 0xd9,
	0x1a, 0x9e, 0xbe, 0xe7, 0x4a, 0x54, 0xb2, 0xf5, 0x48, 0x8e, 0xaf, 0xb1, 0x38, 0x84, 0x58, 0xc8,
	0x9f, 0x27, 0xe7, 0xa7, 0xc1, 0x6d, 0xe8, 0x90, 0x41, 0x6c, 0x7f, 0x3b, 0x60, 0x10, 0x01, 0x4e,
	0x44, 0x6b, 0x80, 0xc2, 0xc6, 0x61, 0x4c, 0x8b, 0x19, 0x4c, 0x06, 0x1d, 0x26, 0x9c, 0x0f, 0x1b,
	0x36, 0x84, 0x83, 0xab, 0xb4, 0xcd, 0x4a, 0xab, 0x46, 0xb2, 0x0b, 0x78, 0xde, 0xce, 0x9d, 0xb1,
	0xf3, 0xd5, 0x87, 0xd7, 0xf3, 0xb9, 0xae, 0x6b, 0xae, 0xc4, 0x7d, 0xc2, 0xc6, 0x00, 0x4b, 0x53,
	0x7f, 0xe4, 0x97, 0x95, 0xe6, 0xc2, 0x8b, 0x4b, 0xa8, 0x37, 0x71, 0xaf, 0xe2, 0x12, 0xf2, 0xb1,
	0x64, 0xe4, 0x6b, 0x36, 0x81, 0xf1, 0x6d, 0x64, 0x41, 0xce, 0x1b, 0xc0, 0x16, 0x71, 0x62, 0x8c,
	0x36, 0xf7, 0x69, 0x38, 0x80, 0x3d, 0xe9, 0x70, 0x9e, 0x24, 0xa5, 0xb6, 0x61, 0xcf, 0xba, 0x84,
	0xc3, 0x8d, 0xf6, 0xf4, 0xf1, 0xbf, 0x08, 0x9e, 0x9c, 0x49, 0xfb, 0x4b, 0x9b, 0x8b, 0xb9, 0x56,
	0xd6, 0xe8, 0xaa, 0x92, 0x06, 0xe7, 0x90, 0xf5, 0x73, 0xc1, 0x43, 0x97, 0xdd, 0x0d, 0x0f, 0x34,
	0xca, 0xaf, 0x2f, 0x82, 0xe6, 0x07, 0xc8, 0x61, 0x78, 0xb3, 0x2f, 0x7c, 0xb1, 0xfd, 0xea, 0x96,
	0x80, 0x47, 0xec, 0x2e, 0xc8, 0x86, 0xe2, 0x15, 0xec, 0xf7, 0x4c, 0xe1, 0x70, 0xfb, 0x51, 0x3f,
	0xa9, 0xd1, 0xe1, 0xb5, 0x79, 0x77, 0x61, 0x11, 0xfb, 0x5f, 0xfd, 0xe5, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x6b, 0xe9, 0x87, 0x48, 0xf6, 0x03, 0x00, 0x00,
}
