// Code generated by protoc-gen-go.
// source: channel.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateChannelRequest struct {
	ChannelListID int64 `protobuf:"varint,1,opt,name=channelListID" json:"channelListID,omitempty"`
	Channel       int64 `protobuf:"varint,2,opt,name=channel" json:"channel,omitempty"`
	Frequency     int64 `protobuf:"varint,3,opt,name=frequency" json:"frequency,omitempty"`
}

func (m *CreateChannelRequest) Reset()                    { *m = CreateChannelRequest{} }
func (m *CreateChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateChannelRequest) ProtoMessage()               {}
func (*CreateChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type CreateChannelResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateChannelResponse) Reset()                    { *m = CreateChannelResponse{} }
func (m *CreateChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateChannelResponse) ProtoMessage()               {}
func (*CreateChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type GetChannelRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetChannelRequest) Reset()                    { *m = GetChannelRequest{} }
func (m *GetChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*GetChannelRequest) ProtoMessage()               {}
func (*GetChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type GetChannelResponse struct {
	Id            int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ChannelListID int64 `protobuf:"varint,2,opt,name=channelListID" json:"channelListID,omitempty"`
	Channel       int64 `protobuf:"varint,3,opt,name=channel" json:"channel,omitempty"`
	Frequency     int64 `protobuf:"varint,4,opt,name=frequency" json:"frequency,omitempty"`
}

func (m *GetChannelResponse) Reset()                    { *m = GetChannelResponse{} }
func (m *GetChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*GetChannelResponse) ProtoMessage()               {}
func (*GetChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type UpdateChannelRequest struct {
	Id            int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ChannelListID int64 `protobuf:"varint,2,opt,name=channelListID" json:"channelListID,omitempty"`
	Channel       int64 `protobuf:"varint,3,opt,name=channel" json:"channel,omitempty"`
	Frequency     int64 `protobuf:"varint,4,opt,name=frequency" json:"frequency,omitempty"`
}

func (m *UpdateChannelRequest) Reset()                    { *m = UpdateChannelRequest{} }
func (m *UpdateChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateChannelRequest) ProtoMessage()               {}
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

type UpdateChannelResponse struct {
}

func (m *UpdateChannelResponse) Reset()                    { *m = UpdateChannelResponse{} }
func (m *UpdateChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateChannelResponse) ProtoMessage()               {}
func (*UpdateChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

type DeleteChannelRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteChannelRequest) Reset()                    { *m = DeleteChannelRequest{} }
func (m *DeleteChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteChannelRequest) ProtoMessage()               {}
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

type DeleteChannelResponse struct {
}

func (m *DeleteChannelResponse) Reset()                    { *m = DeleteChannelResponse{} }
func (m *DeleteChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteChannelResponse) ProtoMessage()               {}
func (*DeleteChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

type ListChannelsByChannelListRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListChannelsByChannelListRequest) Reset()         { *m = ListChannelsByChannelListRequest{} }
func (m *ListChannelsByChannelListRequest) String() string { return proto.CompactTextString(m) }
func (*ListChannelsByChannelListRequest) ProtoMessage()    {}
func (*ListChannelsByChannelListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{8}
}

type ListChannelsByChannelListResponse struct {
	Result []*GetChannelResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListChannelsByChannelListResponse) Reset()         { *m = ListChannelsByChannelListResponse{} }
func (m *ListChannelsByChannelListResponse) String() string { return proto.CompactTextString(m) }
func (*ListChannelsByChannelListResponse) ProtoMessage()    {}
func (*ListChannelsByChannelListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{9}
}

func (m *ListChannelsByChannelListResponse) GetResult() []*GetChannelResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateChannelRequest)(nil), "api.CreateChannelRequest")
	proto.RegisterType((*CreateChannelResponse)(nil), "api.CreateChannelResponse")
	proto.RegisterType((*GetChannelRequest)(nil), "api.GetChannelRequest")
	proto.RegisterType((*GetChannelResponse)(nil), "api.GetChannelResponse")
	proto.RegisterType((*UpdateChannelRequest)(nil), "api.UpdateChannelRequest")
	proto.RegisterType((*UpdateChannelResponse)(nil), "api.UpdateChannelResponse")
	proto.RegisterType((*DeleteChannelRequest)(nil), "api.DeleteChannelRequest")
	proto.RegisterType((*DeleteChannelResponse)(nil), "api.DeleteChannelResponse")
	proto.RegisterType((*ListChannelsByChannelListRequest)(nil), "api.ListChannelsByChannelListRequest")
	proto.RegisterType((*ListChannelsByChannelListResponse)(nil), "api.ListChannelsByChannelListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Channel service

type ChannelClient interface {
	// Create creates the given channel.
	Create(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateChannelResponse, error)
	// Get returns the channel matching the given id.
	Get(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*GetChannelResponse, error)
	// Update updates the given channel.
	Update(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*UpdateChannelResponse, error)
	// Delete deletes the channel matching the given id.
	Delete(ctx context.Context, in *DeleteChannelRequest, opts ...grpc.CallOption) (*DeleteChannelResponse, error)
	// ListByChannelList lists the channels matching the given channel-list id.
	ListByChannelList(ctx context.Context, in *ListChannelsByChannelListRequest, opts ...grpc.CallOption) (*ListChannelsByChannelListResponse, error)
}

type channelClient struct {
	cc *grpc.ClientConn
}

func NewChannelClient(cc *grpc.ClientConn) ChannelClient {
	return &channelClient{cc}
}

func (c *channelClient) Create(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateChannelResponse, error) {
	out := new(CreateChannelResponse)
	err := grpc.Invoke(ctx, "/api.Channel/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) Get(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*GetChannelResponse, error) {
	out := new(GetChannelResponse)
	err := grpc.Invoke(ctx, "/api.Channel/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) Update(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*UpdateChannelResponse, error) {
	out := new(UpdateChannelResponse)
	err := grpc.Invoke(ctx, "/api.Channel/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) Delete(ctx context.Context, in *DeleteChannelRequest, opts ...grpc.CallOption) (*DeleteChannelResponse, error) {
	out := new(DeleteChannelResponse)
	err := grpc.Invoke(ctx, "/api.Channel/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) ListByChannelList(ctx context.Context, in *ListChannelsByChannelListRequest, opts ...grpc.CallOption) (*ListChannelsByChannelListResponse, error) {
	out := new(ListChannelsByChannelListResponse)
	err := grpc.Invoke(ctx, "/api.Channel/ListByChannelList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Channel service

type ChannelServer interface {
	// Create creates the given channel.
	Create(context.Context, *CreateChannelRequest) (*CreateChannelResponse, error)
	// Get returns the channel matching the given id.
	Get(context.Context, *GetChannelRequest) (*GetChannelResponse, error)
	// Update updates the given channel.
	Update(context.Context, *UpdateChannelRequest) (*UpdateChannelResponse, error)
	// Delete deletes the channel matching the given id.
	Delete(context.Context, *DeleteChannelRequest) (*DeleteChannelResponse, error)
	// ListByChannelList lists the channels matching the given channel-list id.
	ListByChannelList(context.Context, *ListChannelsByChannelListRequest) (*ListChannelsByChannelListResponse, error)
}

func RegisterChannelServer(s *grpc.Server, srv ChannelServer) {
	s.RegisterService(&_Channel_serviceDesc, srv)
}

func _Channel_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Channel/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).Create(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Channel/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).Get(ctx, req.(*GetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Channel/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).Update(ctx, req.(*UpdateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Channel/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).Delete(ctx, req.(*DeleteChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_ListByChannelList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsByChannelListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).ListByChannelList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Channel/ListByChannelList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).ListByChannelList(ctx, req.(*ListChannelsByChannelListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Channel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Channel",
	HandlerType: (*ChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Channel_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Channel_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Channel_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Channel_Delete_Handler,
		},
		{
			MethodName: "ListByChannelList",
			Handler:    _Channel_ListByChannelList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor2,
}

func init() { proto.RegisterFile("channel.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0xd3, 0x96, 0x94, 0x7c, 0xf3, 0x45, 0x0d, 0x9b, 0x02, 0xa5, 0x21, 0x11, 0xab, 0x22,
	0xe1, 0x40, 0x23, 0xde, 0x3c, 0x0a, 0x89, 0x31, 0xf1, 0x44, 0xf0, 0x64, 0x4c, 0xac, 0xb0, 0x62,
	0x93, 0xa6, 0xad, 0xed, 0x62, 0x42, 0x8c, 0x17, 0xe2, 0x91, 0x9b, 0x8f, 0xe6, 0x2b, 0xf8, 0x20,
	0xb6, 0xdb, 0x55, 0x60, 0xbb, 0xd0, 0x9b, 0xb7, 0xb2, 0x33, 0xfb, 0x9f, 0xdf, 0xcc, 0x7f, 0x16,
	0xd8, 0x19, 0x3d, 0xd9, 0x9e, 0x87, 0xdd, 0x4e, 0x10, 0xfa, 0xc4, 0x47, 0x8a, 0x1d, 0x38, 0x46,
	0x7d, 0xe2, 0xfb, 0x13, 0x17, 0x5b, 0xf1, 0xb7, 0x15, 0x07, 0x7d, 0x62, 0x13, 0xc7, 0xf7, 0xa2,
	0x34, 0xc5, 0x24, 0xa0, 0xf5, 0x42, 0x6c, 0x13, 0xdc, 0x4b, 0x6f, 0x0e, 0xf0, 0xf3, 0x14, 0x47,
	0x04, 0x1d, 0xfd, 0x6a, 0x5d, 0x3b, 0x11, 0xb9, 0xea, 0xeb, 0x52, 0x43, 0x6a, 0x29, 0x83, 0xf5,
	0x43, 0xa4, 0x43, 0x91, 0x1d, 0xe8, 0x32, 0x8d, 0xff, 0xfc, 0x44, 0x75, 0xf8, 0xf7, 0x18, 0x26,
	0x5a, 0xde, 0x68, 0xa6, 0x2b, 0x34, 0xb6, 0x3c, 0x30, 0x4f, 0xa0, 0xcc, 0x55, 0x8d, 0x82, 0x98,
	0x09, 0xa3, 0x5d, 0x90, 0x9d, 0x31, 0xab, 0x15, 0x7f, 0x99, 0x87, 0x50, 0xba, 0xc4, 0x84, 0x63,
	0xe3, 0x93, 0xe6, 0x12, 0xa0, 0xd5, 0x2c, 0xb1, 0x56, 0xb6, 0x25, 0x39, 0xa7, 0x25, 0x65, 0x4b,
	0x4b, 0x05, 0xbe, 0xa5, 0x77, 0x09, 0xb4, 0x9b, 0x60, 0x9c, 0x9d, 0xe4, 0xdf, 0x62, 0x54, 0xa1,
	0xcc, 0x51, 0xa4, 0xd3, 0x30, 0x9b, 0xa0, 0xf5, 0xb1, 0x8b, 0xf3, 0xf0, 0x12, 0x01, 0x2e, 0x8f,
	0x09, 0x74, 0xa1, 0x91, 0xb0, 0xb1, 0xe3, 0xe8, 0x62, 0xd6, 0x5b, 0x02, 0x6f, 0x12, 0x1b, 0xc2,
	0xc1, 0x96, 0x3b, 0xcc, 0x27, 0x0b, 0xd4, 0x10, 0x47, 0x53, 0x97, 0xc4, 0x93, 0x50, 0x5a, 0xff,
	0xbb, 0xd5, 0x4e, 0xbc, 0xaa, 0x9d, 0xac, 0xa1, 0x03, 0x96, 0xd6, 0x5d, 0x14, 0xa0, 0xc8, 0x62,
	0xe8, 0x16, 0xd4, 0x74, 0x93, 0x50, 0x8d, 0x5e, 0x13, 0x2d, 0xb3, 0x61, 0x88, 0x42, 0xac, 0x2d,
	0x63, 0xfe, 0xf9, 0xf5, 0x21, 0x6b, 0xe6, 0x1e, 0x7d, 0x20, 0x2f, 0xa7, 0x16, 0x9b, 0xf3, 0xb9,
	0xd4, 0x46, 0x43, 0x50, 0x62, 0x0c, 0x54, 0xc9, 0x00, 0xa5, 0xb2, 0x9b, 0x40, 0xcd, 0x3a, 0xd5,
	0xac, 0x20, 0x8d, 0xd3, 0xb4, 0x5e, 0x9d, 0xf1, 0x1b, 0xba, 0x07, 0x35, 0xb5, 0x88, 0x21, 0x8b,
	0xb6, 0x86, 0x21, 0x8b, 0xad, 0xdc, 0xa7, 0xf2, 0x35, 0x43, 0x28, 0x9f, 0x70, 0xdf, 0x81, 0x9a,
	0x7a, 0xc8, 0x2a, 0x88, 0x8c, 0x67, 0x15, 0xc4, 0x5e, 0xb3, 0x06, 0xda, 0xe2, 0x06, 0x16, 0x12,
	0x94, 0x12, 0x07, 0xd7, 0xec, 0x44, 0xc7, 0x54, 0x2f, 0x6f, 0x45, 0x8c, 0x66, 0x5e, 0x1a, 0x43,
	0x68, 0x51, 0x04, 0x13, 0x35, 0x78, 0x84, 0x95, 0x77, 0x42, 0x71, 0x1e, 0x54, 0xfa, 0x4f, 0x76,
	0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x77, 0x63, 0xeb, 0xfd, 0x04, 0x00, 0x00,
}
