// Code generated by protoc-gen-go.
// source: node.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateNodeRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppEUI
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// hex encoded AppKey
	AppKey        string `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	RxDelay       uint32 `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset   uint32 `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	ChannelListID int64  `protobuf:"varint,6,opt,name=channelListID" json:"channelListID,omitempty"`
}

func (m *CreateNodeRequest) Reset()                    { *m = CreateNodeRequest{} }
func (m *CreateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeRequest) ProtoMessage()               {}
func (*CreateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type CreateNodeResponse struct {
}

func (m *CreateNodeResponse) Reset()                    { *m = CreateNodeResponse{} }
func (m *CreateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeResponse) ProtoMessage()               {}
func (*CreateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type GetNodeRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *GetNodeRequest) Reset()                    { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()               {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type GetNodeResponse struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppEUI
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// hex encoded AppKey
	AppKey        string `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	RxDelay       uint32 `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset   uint32 `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	ChannelListID int64  `protobuf:"varint,6,opt,name=channelListID" json:"channelListID,omitempty"`
}

func (m *GetNodeResponse) Reset()                    { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()               {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type DeleteNodeRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *DeleteNodeRequest) Reset()                    { *m = DeleteNodeRequest{} }
func (m *DeleteNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeRequest) ProtoMessage()               {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type DeleteNodeResponse struct {
}

func (m *DeleteNodeResponse) Reset()                    { *m = DeleteNodeResponse{} }
func (m *DeleteNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeResponse) ProtoMessage()               {}
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type ListNodeRequest struct {
	Limit  int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *ListNodeRequest) Reset()                    { *m = ListNodeRequest{} }
func (m *ListNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*ListNodeRequest) ProtoMessage()               {}
func (*ListNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type ListNodeResponse struct {
	TotalCount int64              `protobuf:"varint,1,opt,name=totalCount" json:"totalCount,omitempty"`
	Result     []*GetNodeResponse `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
}

func (m *ListNodeResponse) Reset()                    { *m = ListNodeResponse{} }
func (m *ListNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*ListNodeResponse) ProtoMessage()               {}
func (*ListNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ListNodeResponse) GetResult() []*GetNodeResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListNodeByAppEUIRequest struct {
	Limit  int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// hex encoded AppEUI
	AppEUI string `protobuf:"bytes,3,opt,name=appEUI" json:"appEUI,omitempty"`
}

func (m *ListNodeByAppEUIRequest) Reset()                    { *m = ListNodeByAppEUIRequest{} }
func (m *ListNodeByAppEUIRequest) String() string            { return proto.CompactTextString(m) }
func (*ListNodeByAppEUIRequest) ProtoMessage()               {}
func (*ListNodeByAppEUIRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type UpdateNodeRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
	// hex encoded AppEUI
	AppEUI string `protobuf:"bytes,2,opt,name=appEUI" json:"appEUI,omitempty"`
	// hex encoded AppKey
	AppKey        string `protobuf:"bytes,3,opt,name=appKey" json:"appKey,omitempty"`
	RxDelay       uint32 `protobuf:"varint,4,opt,name=rxDelay" json:"rxDelay,omitempty"`
	Rx1DROffset   uint32 `protobuf:"varint,5,opt,name=rx1DROffset" json:"rx1DROffset,omitempty"`
	ChannelListID int64  `protobuf:"varint,6,opt,name=channelListID" json:"channelListID,omitempty"`
}

func (m *UpdateNodeRequest) Reset()                    { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()               {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type UpdateNodeResponse struct {
}

func (m *UpdateNodeResponse) Reset()                    { *m = UpdateNodeResponse{} }
func (m *UpdateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeResponse) ProtoMessage()               {}
func (*UpdateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type FlushTXPayloadQueueRequest struct {
	// hex encoded DevEUI
	DevEUI string `protobuf:"bytes,1,opt,name=devEUI" json:"devEUI,omitempty"`
}

func (m *FlushTXPayloadQueueRequest) Reset()                    { *m = FlushTXPayloadQueueRequest{} }
func (m *FlushTXPayloadQueueRequest) String() string            { return proto.CompactTextString(m) }
func (*FlushTXPayloadQueueRequest) ProtoMessage()               {}
func (*FlushTXPayloadQueueRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type FlushTXPayloadQueueResponse struct {
}

func (m *FlushTXPayloadQueueResponse) Reset()                    { *m = FlushTXPayloadQueueResponse{} }
func (m *FlushTXPayloadQueueResponse) String() string            { return proto.CompactTextString(m) }
func (*FlushTXPayloadQueueResponse) ProtoMessage()               {}
func (*FlushTXPayloadQueueResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func init() {
	proto.RegisterType((*CreateNodeRequest)(nil), "api.CreateNodeRequest")
	proto.RegisterType((*CreateNodeResponse)(nil), "api.CreateNodeResponse")
	proto.RegisterType((*GetNodeRequest)(nil), "api.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "api.GetNodeResponse")
	proto.RegisterType((*DeleteNodeRequest)(nil), "api.DeleteNodeRequest")
	proto.RegisterType((*DeleteNodeResponse)(nil), "api.DeleteNodeResponse")
	proto.RegisterType((*ListNodeRequest)(nil), "api.ListNodeRequest")
	proto.RegisterType((*ListNodeResponse)(nil), "api.ListNodeResponse")
	proto.RegisterType((*ListNodeByAppEUIRequest)(nil), "api.ListNodeByAppEUIRequest")
	proto.RegisterType((*UpdateNodeRequest)(nil), "api.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeResponse)(nil), "api.UpdateNodeResponse")
	proto.RegisterType((*FlushTXPayloadQueueRequest)(nil), "api.FlushTXPayloadQueueRequest")
	proto.RegisterType((*FlushTXPayloadQueueResponse)(nil), "api.FlushTXPayloadQueueResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Node service

type NodeClient interface {
	// Create creates the given node.
	Create(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	// Get returns the node for the requested DevEUI.
	Get(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// Delete deletes the node matching the given DevEUI.
	Delete(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	// List lists the nodes.
	List(ctx context.Context, in *ListNodeRequest, opts ...grpc.CallOption) (*ListNodeResponse, error)
	// ListByAppEUI lists the nodes by given AppEUI.
	ListByAppEUI(ctx context.Context, in *ListNodeByAppEUIRequest, opts ...grpc.CallOption) (*ListNodeResponse, error)
	// Update updates the node matching the given DevEUI.
	Update(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	// FlushTXPayloadQueue flushes the tx payload queue for the given DevEUI.
	FlushTXPayloadQueue(ctx context.Context, in *FlushTXPayloadQueueRequest, opts ...grpc.CallOption) (*FlushTXPayloadQueueResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Create(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	out := new(CreateNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Get(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Delete(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	out := new(DeleteNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) List(ctx context.Context, in *ListNodeRequest, opts ...grpc.CallOption) (*ListNodeResponse, error) {
	out := new(ListNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ListByAppEUI(ctx context.Context, in *ListNodeByAppEUIRequest, opts ...grpc.CallOption) (*ListNodeResponse, error) {
	out := new(ListNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/ListByAppEUI", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Update(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	out := new(UpdateNodeResponse)
	err := grpc.Invoke(ctx, "/api.Node/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) FlushTXPayloadQueue(ctx context.Context, in *FlushTXPayloadQueueRequest, opts ...grpc.CallOption) (*FlushTXPayloadQueueResponse, error) {
	out := new(FlushTXPayloadQueueResponse)
	err := grpc.Invoke(ctx, "/api.Node/FlushTXPayloadQueue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	// Create creates the given node.
	Create(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	// Get returns the node for the requested DevEUI.
	Get(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// Delete deletes the node matching the given DevEUI.
	Delete(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	// List lists the nodes.
	List(context.Context, *ListNodeRequest) (*ListNodeResponse, error)
	// ListByAppEUI lists the nodes by given AppEUI.
	ListByAppEUI(context.Context, *ListNodeByAppEUIRequest) (*ListNodeResponse, error)
	// Update updates the node matching the given DevEUI.
	Update(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error)
	// FlushTXPayloadQueue flushes the tx payload queue for the given DevEUI.
	FlushTXPayloadQueue(context.Context, *FlushTXPayloadQueueRequest) (*FlushTXPayloadQueueResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Create(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Get(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Delete(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).List(ctx, req.(*ListNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ListByAppEUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeByAppEUIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ListByAppEUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/ListByAppEUI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ListByAppEUI(ctx, req.(*ListNodeByAppEUIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Update(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_FlushTXPayloadQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushTXPayloadQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).FlushTXPayloadQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/FlushTXPayloadQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).FlushTXPayloadQueue(ctx, req.(*FlushTXPayloadQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Node_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Node_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Node_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Node_List_Handler,
		},
		{
			MethodName: "ListByAppEUI",
			Handler:    _Node_ListByAppEUI_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Node_Update_Handler,
		},
		{
			MethodName: "FlushTXPayloadQueue",
			Handler:    _Node_FlushTXPayloadQueue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("node.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xe3, 0xc4, 0x88, 0x69, 0x4b, 0xc9, 0x36, 0x6d, 0x2c, 0xd3, 0xd0, 0xc8, 0x2a, 0x28,
	0x0a, 0x55, 0xac, 0x86, 0x9e, 0x7a, 0x41, 0xd0, 0x00, 0xaa, 0x40, 0x14, 0x2c, 0x2a, 0x55, 0x70,
	0x00, 0xd3, 0x6c, 0x5b, 0x4b, 0x26, 0x6b, 0xe2, 0x75, 0x95, 0x28, 0x8a, 0x90, 0x38, 0xf0, 0x02,
	0x3c, 0x0e, 0xe2, 0xce, 0x9d, 0x57, 0xe0, 0x41, 0xd8, 0xbf, 0x94, 0x4d, 0xec, 0x88, 0x8a, 0x5b,
	0x6f, 0x9e, 0xcf, 0x33, 0xdf, 0xcc, 0xce, 0x7c, 0xb3, 0x0b, 0xd0, 0x23, 0x5d, 0xdc, 0x8a, 0xfb,
	0x84, 0x12, 0x64, 0x06, 0x71, 0xe8, 0xac, 0x9f, 0x12, 0x72, 0x1a, 0x61, 0x8f, 0x7d, 0x7b, 0x41,
	0xaf, 0x47, 0x68, 0x40, 0x43, 0xd2, 0x4b, 0xa4, 0x8b, 0xfb, 0xc3, 0x80, 0xf2, 0x5e, 0x1f, 0x07,
	0x14, 0xbf, 0x60, 0x71, 0x3e, 0xfe, 0x94, 0xe2, 0x84, 0xa2, 0x35, 0xb0, 0xba, 0xf8, 0xfc, 0xf1,
	0xe1, 0xbe, 0x6d, 0xd4, 0x8d, 0xc6, 0x75, 0x5f, 0x59, 0x1c, 0x0f, 0xe2, 0x98, 0xe3, 0x05, 0x89,
	0x4b, 0x4b, 0xe1, 0xcf, 0xf0, 0xd0, 0x36, 0x2f, 0x70, 0x66, 0x21, 0x1b, 0xae, 0xf5, 0x07, 0x1d,
	0x1c, 0x05, 0x43, 0xbb, 0xc8, 0x7e, 0x2c, 0xf9, 0x13, 0x13, 0xd5, 0x61, 0xa1, 0x3f, 0xd8, 0xee,
	0xf8, 0x07, 0x27, 0x27, 0x09, 0xa6, 0x76, 0x49, 0xfc, 0xd5, 0x21, 0xb4, 0x09, 0x4b, 0xc7, 0x67,
	0xac, 0x60, 0x1c, 0x3d, 0x0f, 0x13, 0xba, 0xdf, 0xb1, 0x2d, 0xe6, 0x63, 0xfa, 0xd3, 0xa0, 0x5b,
	0x01, 0xa4, 0x97, 0x9f, 0xc4, 0xec, 0x68, 0xd8, 0x6d, 0xc0, 0x8d, 0xa7, 0x98, 0x5e, 0xe2, 0x44,
	0xee, 0x77, 0x03, 0x96, 0x2f, 0x5c, 0x65, 0xf4, 0x15, 0x3a, 0xfd, 0x3d, 0x28, 0x33, 0x42, 0x7c,
	0xa9, 0xe1, 0xf1, 0x56, 0xe9, 0xce, 0xaa, 0x55, 0x0f, 0x60, 0x99, 0x93, 0xe9, 0x04, 0x15, 0x28,
	0x45, 0xe1, 0xc7, 0x90, 0x8a, 0x78, 0xd3, 0x97, 0x06, 0xa7, 0x25, 0xb2, 0xdc, 0x82, 0x80, 0x95,
	0xe5, 0xbe, 0x87, 0x9b, 0x7f, 0x09, 0x54, 0x07, 0x6f, 0x03, 0x50, 0x26, 0xb4, 0x68, 0x8f, 0xa4,
	0xbd, 0x09, 0x8d, 0x86, 0xa0, 0x2d, 0xb0, 0xfa, 0x38, 0x49, 0x23, 0xce, 0x65, 0x36, 0x16, 0xda,
	0x95, 0x16, 0x53, 0x67, 0x6b, 0x66, 0x0e, 0xbe, 0xf2, 0x71, 0xdf, 0x41, 0x75, 0x92, 0xe1, 0xd1,
	0xf0, 0xa1, 0xe8, 0xf9, 0x7f, 0x95, 0xaa, 0x0d, 0xd0, 0xd4, 0x07, 0x28, 0x96, 0xe0, 0x30, 0xee,
	0x5e, 0xe5, 0x25, 0xd0, 0xcb, 0x57, 0x93, 0xdd, 0x01, 0xe7, 0x49, 0x94, 0x26, 0x67, 0xaf, 0x8f,
	0x5e, 0x06, 0xc3, 0x88, 0x04, 0xdd, 0x57, 0x29, 0x4e, 0xff, 0xa9, 0x92, 0x1a, 0xdc, 0xca, 0x8d,
	0x92, 0xa4, 0xed, 0x9f, 0x25, 0x28, 0xf2, 0x2c, 0xc8, 0x07, 0x4b, 0x2e, 0x1e, 0x5a, 0x13, 0xc3,
	0xcb, 0x5c, 0x22, 0x4e, 0x35, 0x83, 0xab, 0xc2, 0xaa, 0x5f, 0x7e, 0xfd, 0xfe, 0x56, 0x28, 0xbb,
	0x8b, 0xe2, 0x4e, 0x3a, 0xdf, 0xf6, 0xf8, 0x95, 0xb5, 0x6b, 0x34, 0xd1, 0x01, 0x98, 0x4c, 0x03,
	0x68, 0x65, 0x5a, 0x0d, 0x92, 0x2d, 0x57, 0x22, 0x6e, 0x4d, 0x50, 0x55, 0xd1, 0xaa, 0x4e, 0xe5,
	0x8d, 0xe4, 0x59, 0xc6, 0xe8, 0x08, 0x2c, 0x29, 0x79, 0x55, 0x64, 0x66, 0x59, 0x54, 0x91, 0x39,
	0x7b, 0xa1, 0x98, 0x9b, 0x73, 0x98, 0xdf, 0x40, 0x91, 0x37, 0x1f, 0xc9, 0xb2, 0x66, 0x36, 0xc8,
	0x59, 0x9d, 0x41, 0x15, 0xe7, 0x1d, 0xc1, 0xb9, 0x81, 0x6a, 0xd3, 0x9c, 0x52, 0x9d, 0x63, 0x6f,
	0x24, 0xd4, 0x3b, 0x46, 0x9f, 0x61, 0x91, 0x87, 0x4e, 0xb4, 0x8e, 0xd6, 0xa7, 0xd8, 0x66, 0x56,
	0x60, 0x5e, 0xae, 0x5d, 0x91, 0x6b, 0x07, 0xb5, 0xa7, 0x72, 0x31, 0x49, 0x46, 0xe1, 0xb1, 0x78,
	0x01, 0xbc, 0x91, 0xd4, 0xed, 0x38, 0x5b, 0xc0, 0x5b, 0xb0, 0xa4, 0x9e, 0x54, 0xdb, 0x32, 0xbb,
	0xa1, 0xda, 0x96, 0x23, 0xba, 0xba, 0x48, 0xeb, 0x38, 0xf9, 0x6d, 0xe3, 0x43, 0xfe, 0x6a, 0xc0,
	0x4a, 0x8e, 0xc2, 0xd0, 0x86, 0xa0, 0x9c, 0xaf, 0x58, 0xa7, 0x3e, 0xdf, 0x41, 0x25, 0xdf, 0x12,
	0xc9, 0xef, 0x36, 0x37, 0x73, 0x93, 0x7b, 0x74, 0xa0, 0x47, 0x7d, 0xb0, 0xc4, 0x0b, 0x78, 0xff,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x41, 0xcf, 0x1a, 0x32, 0x07, 0x00, 0x00,
}
